Kommunicate-io/Kommunicate-Android-Chat-SDK

- app/src/main/java/kommunicate/io/sample/MainActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java
* To avoid confusion, Login as visitor button has been added where the user can just click on the button and login to the app
* Info text is also provided below the button so that the user understands the difference.
**Apart from this:**
* If the user forgets to set the application key in the gradle file, an error dialog with will thrown mentioning that the Application key is not set and instructions to set it.
* A launchChat method has also been removed from deprecated tag as it is still used
* Fixed a crash fr broadcast type groups in the agent app.
**These are tested on Local device.**
> Add option for visitor login in sample app

- app/src/main/java/kommunicate/io/sample/MainActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values/strings.xml
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java
* To avoid confusion, Login as visitor button has been added where the user can just click on the button and login to the app
* Info text is also provided below the button so that the user understands the difference.
* A launchChat method has also been removed from deprecated tag as it is still used
* This is tested on Local device.
> add login as visitor button in sample app

- app/build.gradle
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/layout/km_take_over_from_bot_dialog.xml
- kommunicateui/src/main/res/values/mobicom_strings.xml
1) Added a dialog that will block the UI access until take over from bot has not finished
2) Also decreased the clickable area in the take from bot button in the dialog
Tested on Local device
> Add progress dialog while taking over from bot

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmFeedbackView.java
- kommunicateui/src/main/res/layout/feedback_display_layout.xml
added a functionality to feedback integration where the feedback comment becomes scrollable if it is too many lines.
> wrapped feedback comment inside max height scroll view

- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicate/src/main/java/io/kommunicate/database/KmDatabaseHelper.java
* Fix the logout delete data 
* And make 28 target
> Fix logout issue 

- app/build.gradle
- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
1) Fixed issue where storage permission was not being asked for camera
2) disable feedback for agent
3) hide action messages by default for kommunicate SDK
Tested on local device.
> Storage permission fix and hide action messages

- kommunicateui/src/main/AndroidManifest.xml
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/FullScreenImageActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/AlRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/ALRichMessageAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/AlImageAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/AlRichListsAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/callbacks/ALRichMessageListener.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/ALBookingDetailsModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/ALGuestCountModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/ALRichMessageModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/AlHotelBookingModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/views/KmCustomLayoutManager.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/webview/AlWebViewActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/webview/AlWebViewJsInterface.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/KmAutoSuggestionAdapter.java
- kommunicateui/src/main/res/layout/al_rich_message_layout.xml
- kommunicateui/src/main/res/layout/km_activity_payment.xml
- kommunicateui/src/main/res/values/strings.xml
Have refactored rich messaging code so that it becomes easy to copy the changes to applozic sdk.
Fixed issues related to clicks on quick reply actions.
Tested on local device.
> Richmessage improvement 

- app/proguard-rules.pro
- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicate/src/main/java/io/kommunicate/async/KmUserLoginTask.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
1) Fixed crashes from crashlytics
2) Remove deleted groups conversation list
3) update Applozic SDK version to 5.65
4) Changed the sdk organisation to kommunicate
> change Org and fix crashes from crashlytics and 

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/KmAutoSuggestionAdapter.java
Fixed crash when the autosuggestion is clicked.
> fix autosuggestion click crash

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Fixed issue where typing indicator was not working after MQTT disconnection and reconnection
> fix typing indicator issue after mqtt reconnection

- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicate/src/main/res/values/strings.xml
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/ApplozicSetting.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/ApplozicDocumentView.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/AlRichMessage.java
- kommunicateui/src/main/res/layout/km_custom_toolbar_layout.xml
- kommunicateui/src/main/res/values/mobicom_colors.xml
1) Added option to set parent activity dynamically
2) Fixed the submit/quick reply button click in case type is not specified
3) Set the default group name to "Support" from "Kommunicate Support"
4) Fixed the sender side text color in document view
5) Fixed the FAQ button click
> Add option to set dynamic parent activity for ConversationActivity

- app/src/main/java/kommunicate/io/sample/MainActivity.java
- app/src/main/res/values/strings.xml
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicate/src/main/java/io/kommunicate/utils/KmUtils.java
- kommunicate/src/main/res/values/strings.xml
1)Show toast and log for app ID change in Kommunicate.init() function
2) Show error and toast for empty app ID
Tested on local device.
> Show toast for App id change 

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/KmAttachmentsController.java
1) Fixed issue where new user is not able to receive real time messages from MQTT
2) Fixed issue where file upload is not working on first install
> fix mqtt not connecting issue for app version 112

- hooks/checkstyleplugin.sh
- hooks/google_checks.xml
- hooks/pre-push
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/FeedbackInputFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/AlRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmFeedbackView.java
note: 
- Also tested the new code style workflow and modified the checkstyle file accordingly.
- Will add comments to CM-80.
> Change rating values to 1,5,10

- app/src/main/java/kommunicate/io/sample/MainActivity.java
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
Check if the incoming appId is placeHolder, then skip setting it to init function.
> skip setting appId for placeholder appId

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/AlRichMessageFactory.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/ALBookingRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/AlButtonRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/AlRichMessageAdapterFactory.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ButtonAlRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/CardTypeAlRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/FaqAlRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ImageAlRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ListAlRichMessage.java
1) Moved all the specific rich messages into a separate types package
2) Added braces for single line if checks
3) Fixed the clicks for older button types rich messages
> rich message factory code refactoring

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmRMActionModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmRichMessageModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/FormRichMessage.java
Added the generic models with new payload for rich messages.
> add rich message v2 generic models

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/ALRichMessageModel.java
Added the option to change the user language from the click of language selection quick replies.
> Add support for language change bot

- app/src/main/java/kommunicate/io/sample/MainActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/ApplozicAudioManager.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/ApplozicDocumentView.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobiComAttachmentSelectorActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobicomLocationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MessageInfoFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/webview/AlWebViewJsInterface.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/stt/KmTextToSpeech.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/adapters/KmPrechatInputAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmHelper.java
1) Replaced all the default toasts with Kommunicate's Custom toast.
2) Any error message is replaced with error Toast.
3) Any instructional message or success message is replaced with success toast.
> replace the stock toasts with Km custom toast

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MessageInfoFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Fixed issue where multiple messages where being sent on clicking resend option in a message when network is not available.
> fix multiple messages sent on resend

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/helpers/KmFormStateHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
Send data inside formData param within KM_CHAT_CONTEXT in case of postBackToBotPlatform.
> send data inside formData in postBackToBotPlatform

- app/build.gradle
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
1) Replaced the action type check with submit type check in form rich message
2) Keep form data after submit with postBackToBotPlatform
3) Fixed issue where record button was not showing if record option is disabled and speechToText option is enabled
4) Fixed issue where send button was not visible if record option is disabled and no message is typed.
> Replace action type check with submit type check in form

- app/build.gradle
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
* Fixed attachment download option for aws server setting
* Added action type check in Form templates's action
* Release version 2.0.4.1
> Release version V2.0.4.1

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/helpers/KmFormStateHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/KmFormStateModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
- kommunicateui/src/main/res/values/strings.xml
Added support for validation for text fields in form template
> Add support for Form validation

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/helpers/KmFormStateHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/KmFormStateModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
- kommunicateui/src/main/res/values/strings.xml
Added support for validation for text fields in form template
> Add support for text field validation in form template

- app/build.gradle
- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/helpers/KmFormStateHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/KmFormStateModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmHelper.java
- kommunicateui/src/main/res/layout/km_form_item_layout.xml
- kommunicateui/src/main/res/values/strings.xml
All the commits for version 2.0.5
> Release version V2.0.5

- app/src/main/java/kommunicate/io/sample/MainActivity.java
- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicate/src/main/java/io/kommunicate/async/KmGetAgentListTask.java
- kommunicate/src/main/java/io/kommunicate/services/KmClientService.java
- kommunicate/src/main/java/io/kommunicate/services/KmService.java
- kommunicate/src/main/java/io/kommunicate/services/KmUserClientService.java
- kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/ApplozicSetting.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MessageInfoFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/instruction/InstructionUtil.java
* Removed secret keys from shared preference and moved them to secured storage
* Updating theme colors very time the agent list call goes. 
* Fixed issue where user was getting logged out in case of visitor login
> update SDK for security improvements with AL SDK version 5.90

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
* In `KommunicateApplication` class implement the `ALRichMessageListener` and override its method.
* Test the click for form, it should not work
> Fixed issue where agent was able to submit form

- kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/KmBotTypingDelayManager.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Added typing delay for bot messages based on the dashboard setting
> Bot typing delay

- kommunicate/src/main/java/io/kommunicate/async/KmConversationFeedbackTask.java
- kommunicate/src/main/java/io/kommunicate/services/KmClientService.java
- kommunicate/src/main/java/io/kommunicate/services/KmService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
This is done so that feedback is displayed in the dashboard. in feedback v1 It was not being displayed.
NOTE: the message "rated the conversation" being displayed has to be hidden from applozic side.
> CM-556: update feedback api to v2

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
* Change variable and method access in conversation fragment for ease of doing code changes from agent app directly by overriding.
> change variable and method access to protected from private

- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/async/KmDeleteConversationTask.java
- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java
The chat session will be deleted if the user opens the conversation again after the session time has expired.
This will only work when using KmConversationBuilder.
> add support for chat session delete

- app/src/main/assets/applozic-settings.json
- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicate/src/main/java/io/kommunicate/async/KmUserLoginTask.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ChannelCreateActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ChannelInfoActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobiComAttachmentSelectorActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobicomLocationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmButtonRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmCardRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmListRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ButtonKmRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/FaqKmRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ListKmRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/webview/KmWebViewActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/activities/LeadCollectionActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmThemeHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/people/contact/AppContactFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/people/contact/ContactSelectionFragment.java
* Updated applozic sdk version to 5.96. This changes the Async Tasks implementation for tasks accessed from applozic
* Added option to set custom toolbar, status bar and rich message theme colors from applozic-settings.json file.
Toolbar color changes screens:
1) Chat list screen
2) Chat thread screen
3) Location selection screen
Statusbar color changes screens:
1) Chat list screen
2) Chat thread screen
3) Location selection screen
4) Pre chat screen
5) Attachment selection screen
6) Web view screen for FAQ and web link rich messages
Rich messages theme color will change the color for all rich messages.
> More theme customization options

- kommunicateui/src/main/res/layout/mobicom_received_message_list_view.xml
- kommunicateui/src/main/res/layout/mobicom_sent_message_list_view.xml
- kommunicateui/src/main/res/layout/reply_message_layout.xml
* Fixed reply message layout for sent and received messages
> Add reply message support

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
* Fetch away message whenever the assignee changes
> update away message on assignee change

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmAutoSuggestionArrayAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmAutoSuggestion.java
- kommunicateui/src/main/res/layout/km_auto_suggestion_row_layout.xml
- kommunicateui/src/main/res/layout/mobicom_message_list.xml
* Added support for autosuggestion type rich message
* Currently it has implementations for suggestions received in message metadata only
> add support for auto suggestion message

- kommunicate/src/main/java/io/kommunicate/KmCustomEventManager.java
Removed all unused methods from KmEventManager as AL exposes those methods now.
> simpilfy methods is KmEventManager

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
* Here Injecting the Instance of DEtailedConversationAdapter can be done easily into the fragment for customization. 
* The color changes for agents can also be done easily from the agent app
> seperate instance creation of adapter

- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/layout/mobicom_received_message_list_view.xml
* Moved the receiver name text view outside the message box
* Added setting to change the color of the receiver name text view
> move receiver name outside and add setting to change the color

- app/src/main/assets/applozic-settings.json
- kommunicate/src/main/java/io/kommunicate/KmConversationBuilder.java
- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/KmSettings.java
- kommunicate/src/main/java/io/kommunicate/async/KmConversationInfoTask.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/layout/mobicom_received_message_list_view.xml
* Removed automatic updates from conversation builder
* Added methods to update teamId, conversationAssignee and conversationMetadata
* Moved conversation view to different method in detailed conversation adapter
> create seperate methods for conversation update

- kommunicate/src/main/java/io/kommunicate/async/KmGetBotTypeTask.java
- kommunicate/src/main/java/io/kommunicate/services/KmUserClientService.java
- kommunicate/src/main/java/io/kommunicate/services/KmUserService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Dialog flow bot has a character limit of 256
- Other bots have a character limit of 2000
- ApplicationID not required for bots so safely removed it and tested.
- Fetched from HttpRequestUtils because authorization required.
> [TD-1866] - Dialogflow character limit fix

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/res/layout/km_feedback_agent_layout.xml
- kommunicateui/src/main/res/values/strings.xml
"Rated the conversation" action message was showing up in Agent app. Removed this to implement the new feedback feature in Agent app.
> [TD-1833] - Show feedback in Message View holder to show multiple feedback for Agent app

- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
editTextHintText was in the applozicSettings.json but it was not getting used
> [TD-2141] - Customizable settings fix: EditTextHintText

- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
**Description:**
Have added `CompanySettings` object inside KmAppSettingModel class. 
**Purpose :** 
To get the operator Permission settings for assigning conversations to others.
**Note:**
Tested SDK locally after adding the object.
> [CM-738] Added company settings inside App Settings Object.

- kommunicate/build.gradle
- kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/AlUserUpdateTask.java
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/KmRichMessageFactory.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/VideoRichMessage.java
Changes:
1. App Setting Model for Agent app
2. Rich message video template conflict resolve
3. userUpdateTask constructor for Agent app
> Minor release for bug fix: V2.2.5.1

- CHANGELOG.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- kommunicate/build.gradle
- kommunicate/src/main/AndroidManifest.xml
- kommunicateui/build.gradle
- kommunicateui/src/main/AndroidManifest.xml
> Release for V2.3.0

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/schedule/ScheduledMessageUtil.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/WearableNotificationWithVoice.java
For API 31, pending intent has to be set PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_MUTABLE
> Pending intent change for API 31

- kommunicate/src/main/java/com/applozic/mobicommons/data/AlPrefSettings.java
Saving encrypted password to use in Agent app, for Switch application
> [CM-797] -  Save encrypted password

- kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlEventManager.java
- kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlMessageEvent.java
- kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/listners/KmStatusListener.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Handle the away mqtt message using listener: KmStatusListener 
- KmStatusListener will be used in Agent App to update Away status of Agent as well as end user status.
> [CM-690] - Status listener with mqtt

- kommunicate/src/main/java/com/applozic/mobicommons/encryption/SecurityUtils.java
Added a String empty check to plain key to handle null value
> [CM-782] - Security Utils crash

- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/FeedbackInputFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/layout/feedback_rating_layout.xml
- Added oneTimeRating in applozic-settings.json
- oneTimeRating = true -> Ask for feedback only once in a conversation
- oneTimeRating  = false -> Ask for feedback everytime the conversation is resolved.
> [CM-822] - oneTimeRating feature added

- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
For using it in Agent app, added subscriptionDetails in Company Settings Model
> [ CM-657] added subscriptionDetails in Company Settings Model

- kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlEventManager.java
- kommunicate/src/main/java/io/kommunicate/callbacks/KmPluginEventListener.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
void onStartNewConversation(Integer conversationId);
void onSubmitRatingClick(Integer conversationId, Integer rating, String feedback);
void onMessageSent(Message message);
void onMessageReceived(Message message);
void onBackButtonClicked(boolean isConversationOpened);
> [CM-847] - Add Events to Event listener

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicate/src/main/java/com/applozic/mobicommons/ALSpecificSettings.java
- kommunicate/src/main/java/com/applozic/mobicommons/commons/core/utils/Utils.java
- kommunicateui/build.gradle
- Added EditTextHintText localization
- Fix logging to txt file
> Patch release - V2.3.9

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmRMActionModel.java
- postBackToBotPlatform payload will add the formData inside metadata of the message, which will be sent in the reply message.
- postBackToKommunicate will create a new message with the contents of the form submitted
- postFormDataAsMessage will append the form data in the reply message.
Have compared and tested with chat widget's functionality.
> [CM-920] - support for postBackToBotPlatform and getPostBackToKommunicate

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
added fix for postBackToBotPlatform
> Realase for v2.4.0

- kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/MobiComUserPreference.java
- kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java
- Added support to show notification on Agent app when "Notify everybody" is selected from dashboard.
> [CM-923] - Notify everybody notification for Agent app

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Long pressing a message should show Menu options - Copy, Delete, Info
- Code already exists but it was not working, fixed it.
> [CM-970] - Menu option on long click

- CHANGELOG.md
- app/src/main/AndroidManifest.xml
- kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
Changed notification icon color
> [CM-1007] Changed notification icon color

- CHANGELOG.md
- kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
Added notification body when the rich message only has button and no message to show .
> [CM-1027] Fixed empty body of notification for rich message in some cases

- kommunicate/src/main/java/io/kommunicate/utils/KmUtils.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmCardRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ButtonKmRichMessage.java
- kommunicateui/src/main/res/drawable/ic_messageicon.xml
> [CM-1036] Added a default last message body when last message of a conversation has an empty body

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Fixed showing empty body for the rich message having no text
2) Fix for attachment sending empty message
3) Sync Deleted Messages from dashboard
4) Optimized Group list API
4) Fixed empty notification body
> release changes for v2.4.4

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Added support for HTML Video Rich message
2) Multiple crash fix and optimizations
> Release changes for v2.4.6

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MessageClientService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/values/mobicom_array.xml
- kommunicateui/src/main/res/values/strings.xml
- local.properties
> delete message with sync

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmTypingView.java
- kommunicateui/src/main/res/animator/km_blinking.xml
- kommunicateui/src/main/res/drawable/km_blinking_dot.xml
- kommunicateui/src/main/res/layout/km_typing_indicator_layout.xml
- kommunicateui/src/main/res/layout/mobicom_message_list.xml
The typing indicator in Android SDK was shown on toolbar, whereas on web, it was shown with a typing animation. To maintain consistency over all platform, we have developed the same for Android.
https://user-images.githubusercontent.com/22256112/192432885-f810694b-ecba-4e0c-ae04-50452f768593.mp4
- Design reviewed by Product team
> [CM-1120] - Typing indicator design changes

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Typing Indicator Design Changes
2) SQL Injection vulnerability fix
3) Threads optimized
4) Invalid agent/bot name fix
> release changes for v2.4.8

- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
start new conversation background color customization
> start new conversation background color customization

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- Added Support for API33
- Customisation for `Start New Conversation` Button
> release changes for v2.5.0

- kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlEventManager.java
- kommunicate/src/main/java/io/kommunicate/callbacks/KmPluginEventListener.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/FeedbackInputFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmRecordView.java
Added events:
```java
void onAttachmentClick(String attachmentType);
void onFaqClick(String FaqUrl);
void onLocationClick();
void onNotificationClick(Message message);
void onVoiceButtonClick(String action);
void onRatingEmoticonsClick(Integer ratingValue);
void onRateConversationClick();
```
> [CM-1136] - added multiple events to KmPluginEventListener

- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmAutoSuggestionArrayAdapter.java
- kommunicateui/src/main/res/layout/km_auto_suggestion_row_layout.xml
Auto suggestion button color customization
> [CM-1153] - Auto suggestion button color customization

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Auto Suggestion Button color customization
2) Added support for AES256 encryption and decryption
> release changes for v2.5.3

- kommunicate/src/main/java/io/kommunicate/zendesk/KmZendeskClient.java
1. Transcript messaging sending "Admin created Group Conversation"
2. Listening to chat events even before handoff (causing crash sometimes)
> Minor fix for Zendesk

- kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/MobiComKitBroadcastReceiver.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
Removed the crash from the NotificationService.java line 441 by replacing messageJson from the intent with message's keyString and groupId .
> [CM-1223] Fixed crash at NotificationService.java line 441

- CHANGELOG.md
- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Added a log out option on the conversation menu that can be enabled/disabled from `applozic-settings.json` file
> [CM-1222] Added logout option on conversation menu

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java
- kommunicate/src/main/java/com/applozic/mobicommons/people/channel/Channel.java
We handle notification directly from FCM payload now. There was an issue with that where contacts / channels were getting updated incorrectly. 
Fixed this by creating channel / contacts from FCM payload messages.
> [CM-1261] - Fix notification for agents

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
Fixed agent app toolbar showing conversation assignee image instead of end user image
Fixed notification for agents
> Release changes for v2.6.1

- CHANGELOG.md
- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmRichMessageAdapterFactory.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmVideoRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/CardTypeKmRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/VideoRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/webview/KmWebViewActivity.java
Added option to enable/disable javaScript in webView by changing the `javaScriptEnabled` option in  `applozic-settings.json` file
> [CM-1300] Added option to enable/disable javaScript in webView in Android SDK

- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/zendesk/KmZendeskClient.java
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
1. Restart conversation throwing thread exception on some cases
2. Existing chat not opening
> Fixed Zendesk bugs

- CHANGELOG.md
- app/src/main/assets/applozic-settings.json
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Added support for Multiple Select Button - using custom setting "checkboxAsMultipleButton"
2) Added support to show conversation info view below topbar - using KmConversationInfoSetting class
> release changes for v2.6.8

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Changed Message View layout to Top to Bottom
2) Support for custom toolbar subtitle - using KmConversationInfoSetting class
3) Add support to add top static first message
> Release changes for v2.6.9

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- When postFormDataAsMessage was present, formAction was not getting called.
- Moved formAction API call to different if block
> Fix formAction not getting called

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Prevent rating from being asked everytime a resolved conversation is opened.
- Tested it on the  local device
> [CM-1392] - Fix for rating asked everytime in a resolved conversation

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Fix for rating asked everytime in a resolved conversation
2) Fix formAction not getting called
> release changes for v2.7.0

- kommunicate/src/main/java/com/applozic/mobicomkit/api/attachment/ApplozicMultipartUtility.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/attachment/FileClientService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MessageClientService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/SyncCallService.java
- kommunicate/src/main/java/com/applozic/mobicommons/commons/core/utils/Utils.java
- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/layout/km_rich_message_sender_layout.xml
- To upload all attachments to a specific URL
- We get endpoint from appSettings API
- Tested in webhook
- Tested with Taxbuddy users to confirm correct groupId being sent.
> [CM-1435] -Add custom attachment upload

- kommunicate/src/main/java/io/kommunicate/utils/KmUtils.java
- Restricted SDK usage for pricing plan code 112(monthly start), 113(yearly start).
- If start plan users try to open the conversation screen, it will show suspension screen
> [CM-1431] - Add Restriction for Start Plan in Android SDK

- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- Added flags in companySettings for Team Concepts
> added team concept in companySettings

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- Expose a function to show/hide online, offline,away status of the agent on conversation screen
> release changes for v2.7.3

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
- kommunicateui/src/main/res/drawable/km_home.xml
- kommunicateui/src/main/res/drawable/km_refresh_icon.xml
- kommunicateui/src/main/res/layout/km_custom_toolbar_layout.xml
- kommunicateui/src/main/res/layout/quickconversion_activity.xml
- kommunicateui/src/main/res/values/colors.xml
- kommunicateui/src/main/res/values/styles.xml
- Added Refresh Icon in toolbar - same as iOS
- Added colors for customizing toolbar icon color - It can only be done using colors.xml resource file
`km_toolbar_icon_color` will change color of all icons in the toolbar - Back button, 3 dots, refresh icon
> [CM-1491] - UI/UX changes to match iOS

- kommunicate/src/main/java/com/applozic/mobicomkit/Applozic.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/ApplozicMqttService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/ApplozicMqttIntentService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/channel/service/ChannelService.java
- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- Subscribe to Team topics
- Handle APPLOZIC_42 messages -> to delete channel from DB
- AppSettingModel update for new changes
> [CM-1486] - Changes for team concept

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
> release changes for v2.7.4

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Showing typing indicator when bot is fetching response from an API
> [CM-1472] - Show Typing Indicator while api fetching the response

- kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/UserClientService.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/UserDetail.java
- kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/UserService.java
- kommunicate/src/main/java/com/applozic/mobicommons/people/contact/Contact.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Fix Online/offline Status not correctly updating
- Used "user/v2/detail" API to get contact object
- fixed the issue in which gray status dot is showing when agent is online
> [CM-1514] - Online/offline Status not correctly updating for Taxbuddy

- CHANGELOG.md
- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/MobicomMessageTemplate.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/layout/quickconversion_activity.xml
> [CM-1580] Added customization to center toolbar title and left align message template

- CHANGELOG.md
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
km_conversation_info_view was not needed in the agent app so wrapped the code inside a conditional statement
> [CM-1560] Fixed crash in KmConversationFragment.onCreateView

- CHANGELOG.md
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/res/layout/quickconversion_activity.xml
Reverts Kommunicate-io/Kommunicate-Android-Chat-SDK#426
> Revert "[customizations-for-mg] Fixed toolbar title alignment when menu options are enabled/disabled"

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1. Added customisation to change the option menu icon on Conversation Screen
> Release Changes v2.8.0

- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- If Team Mode is enabled, then subscribe to team topics, otherwise subscribe to Support group topic
> Added team topic subscription in MQTT

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
> Release changes for v2.8.1

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- Fixed crash that was caused by message template
> Release changes for v2.8.2

- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- Added support for new "hideAssigneeChange" flag to show/hide assgineeChange drop down
> [CM-1677] - Team concept part 3

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
> Release Changes for v2.8.3

- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- kommunicate/src/main/java/io/kommunicate/services/KmClientService.java
- Upgraded appsettings api to V3
- Optimised create conversation flow
- Created a function to refresh the appsetttings
- As a result of above three , Able to reduce the create conversation flow
> New appSetting Changes

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java
- kommunicateui/build.gradle
- Reduce time taken for conversation creation
> Release Changes For v2.8.4

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmCardRMAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ButtonKmRichMessage.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ListKmRichMessage.java
- Fixed hidePostCta where quick reply was not hiding after last message in all rich messages
> [CM-1704] - Fixed hidePostCta

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- Fixed submit button opening the webview
> [CM-1666] - FIxed submit button

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
1) Fixed text to speech creating speech before the message received during bot delay
2) Fixed static top message not showing while bot delay is enabled 
3) Fixed static top messag showing on the last when conversation assigned to agent
> Fixed text to speech bug and static top message

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1.  Fixed typing indicator appearing after welcome message was received
2. Fixed hidePostCta
> Release changes for v2.8.5

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Fixed typing indicator appearing after welcome message was received
2) Fixed hidePostCta
> Release Changes for v2.8.6

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/KmFormStateModel.java
Added a default value to prefill selected button in form
```
{
"message": "Submit your details",
"platform": "kommunicate",
"metadata": {
"contentType": "300",
"templateId": "12",
"payload": [
{
"type": "radio",
"data": {
"title": "What do you identify as:",
"name": "Gender",
"options": [
{
"label": "Male",
"value": "male",
"selected": true
},
{
"label": "Female",
"value": "female"
},
{
"label": "Other",
"value": "other"
}
]
}
},
{
"type": "submit",
"data": {
"action": {
"message": "optional- this message will be used as acknowledgement text when user clicks the button",
"postFormDataAsMessage": "true",
"requestType": "json",
"formAction": "<URL>"
},
"type": "submit",
"name": "Submit"
}
}
]
}
}
```
```
{
"message": "Submit your details",
"platform": "kommunicate",
"metadata": { …
```
> [CM-1731] Added a default selection to prefill selected button in form

- CHANGELOG.md
- app/src/main/assets/applozic-settings.json
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
1) Fixed unreadCount returning wrong value
2) Added support of prefill checkboxes on Form Template.
3) Default configuration added for disabling the form submit button using 'disableFormPostSubmit'.
> Release  changes for v2.8.7

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Fixed crash while deleting message on agent app
> Release changes for v2.8.8

- kommunicate/src/main/res/values/strings.xml
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/values/strings.xml
- Restrict Agent messaging after 24 hours inactivity for WhatsApp integration.
> [CM-1215] - Restrict Agent messaging after 24 hours inactivity for WhatsApp integration

- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Added customisation to change mainDivider line colour.
- User can pass required colour in "chatBarTopLineViewColor": "".
> [CM-1777]- Provided Customisation To change mainDivider line colour

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- Due to filterDropdownList method the position of item present in the dropdown list was not in the proper order.
- Made some few changes in the above method so now it will check  ("selected": true) for the items present in the dropdown  list and will return its position.
- This position will now be used to be selected by default and shown on dropdown field.
> [CM-1742]-Fix the random order of item in dropdown list

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
1) Fixed typing indicator for welcome message
2) Fixed "no conversations" showing sometimes for the first time when conversation is created
3) Fix the random order of item in dropdown list
4) Provided customisation To change mainDivider line colour
5) Fixed user messages coming on the right side in agent app
> Release v2.8.9

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- Fixed message status icon colour customisation.
> Release changes for v2.9.0

- kommunicate/src/main/java/io/kommunicate/utils/KmUtils.java
- Fixed File names are converted to '???' for the non-english file name
> File names are converted to ??? when for non-english file name

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Fixed API suggestion for array of object [auto suggestion](https://docs.kommunicate.io/docs/message-types#autosuggestions-in-your-chat-box)
- Fixed multiple api calls for auto suggestion API
> [CM-1851] Fixed autosuggestion

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- Added customisation for multiple attachment selection
- Fixed documents showing incorrect filename for non-english names
> Release changes for v2.9.1

- CHANGELOG.md
- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/res/layout/km_new_channel_custom_message.xml
- kommunicateui/src/main/res/values/strings.xml
Updated conversation assignment message UI and made it similar to web sdk
> [CM-1826] Conversation assignment message UI update

- CHANGELOG.md
- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmRMActionModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java
- Added support for Dialogflow fulfilment form
- Fixed default selection form data only getting selected in the UI and not getting sent with the reply message
```
{
"platform": "kommunicate",
"message": "What are you looking for?",
"metadata": {
"templateId": "12",
"contentType": "300",
"payload": [
{
"name": "choice_type",
"type": "checkbox",
"title": "Please choose from the options.",
"options": [
{
"label": "Business Plan",
"value": "Business Plan",
"selected": true
},
{
"value": "Investor Deck",
"label": "Investor Deck",
"selected": true
},
{
"label": "Company Presentation",
"value": "Company Presentation"
},
{
"value": "Marketing Plan",
"label": "Marketing Plan"
},
{
"value": "Content Strategy",
"label": "Content Strategy"
},
{
"value": "Social  Strategy",
"label": "Social  Strategy" …
```
> [CM-1723] Added support for dialogflow fulfilment form

- CHANGELOG.md
- build.gradle
- kommunicate/build.gradle
- kommunicateui/build.gradle
- Added support for dialogflow fulfilment form
- Fixed agent app not showing notifications after automatic assignment
- Added support for chatwidget disabled flag
- Fixed autosuggestion
- Fixed channel messages showing in SDK
> Release changes for v2.9.2

- app/build.gradle
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/res/layout/quickconversion_activity.xml
- Fixed RTL FAQ button hidden.
- Increased minSdkVersion to 17 in SDK & in sample app.
> [CM-1848] - Fixed RTL FAQ button hidden

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
1) Added support for iframe in HTML type rich message
2) Fixed location issues
3) Image full screen view improvement
4) Added back button in in-app browser
> Release changes for v2.9.4

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java
Fixed issue: HTML or Video Rich message is Not visible in Conversation List Screen | Android SDK
> [CM-1929] HTML or Video Rich message render fix

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java
Fixed issue: Form submission empty message fix | Android SDK
> [CM-1497] form submission empty message fix

- CHANGELOG.md
- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
- Added customization for image compression
- Fixed crash caused by empty form action message when submitting the form
> Release changes for v2.9.5

- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/res/layout/mobicom_message_list.xml
- Added Support for Record Video & Send Feature
- Updated attachment options layout with respect to spacing & order of the options
Follow-Up Tasks:
- Compression 
- adding Limit same as web & iOS
> [CM-1914] Added support for record video & send feature

- app/src/androidTest/java/kommunicate/io/sample/ExampleInstrumentedTest.java
- app/src/main/assets/applozic-settings.json
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ListKmRichMessage.java
- kommunicateui/src/main/res/drawable/icon_attchment_file.xml
- kommunicateui/src/main/res/drawable/icon_camera.xml
- kommunicateui/src/main/res/drawable/icon_gallery.xml
- kommunicateui/src/main/res/drawable/icon_location.xml
- kommunicateui/src/main/res/drawable/icon_video_camera.xml
- kommunicateui/src/main/res/layout/mobicom_message_list.xml
- Fixed List RM rendering issue when element is empty in payload
- Fixed build issue due to last merge(asset are not merged)
- Fixed build issue due to deprecated import statment in test module
> [CM-2005] Fixed List rendering issue & build issue for sample app

- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/KMServerConfiguration.java
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- Added support for EU server config
- IT can be achieved by using below function
```swift
Kommunicate.setServerConfiguration(MainActivity.this, KMServerConfiguration.DEFAULTCONFIGURATION);
```
> [CM-2024]Added support for EU servers

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/FeedbackInputFragment.java
- kommunicateui/src/main/res/layout/feedback_rating_layout.xml
- kommunicateui/src/main/res/values/styles.xml
Fixed issue: Submit Rating Button is not going up when keyboard | Android SDK
> [CM-1843] Submit Rating Button display fix

- kommunicate/src/main/java/io/kommunicate/utils/KmUtils.java
Fixed issue: Text Align for Bottom navigation Fragment | Android Agent app
> [CM-1495] Text Align for Bottom Navigation Fragment fix

- kommunicate/src/main/java/com/applozic/mobicommons/commons/image/ImageLoader.java
Added video thumbnail feature before downloading video completely.
> [CM-1126] Video thumbnail feature support

- app/src/main/AndroidManifest.xml
- kommunicateui/src/main/res/layout/activity_km_location.xml
- Fixed slowness in location loading issue
- Updated Location Activity layout to similar to iOS
> [CM-2030] Fixed delay in map loading & changed the location screen similar to iOS

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java
Earlier same sync api calls were triggered for the a given `lastSyncTime` while refreshing even if we don't have any new messages. Therefore optimized that duplicate sync api calls (/rest/ws/message/sync).
> [CM-1912] - Sync Call API optimisation

- kommunicate/src/main/java/com/applozic/mobicomkit/api/ApplozicMqttService.java
Problem: In Android Agent App Autorefresh option was not working properly.
> Auto refresh chats fix

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/KmDocumentView.java
Fixed the color issue for agent app in document attachments.
> [CM-2037] Color fix for Attachments for Agent app

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- Fixed Textfields got disabled when assignment message comes
> Fixed Form fields are disabled after assignment messages

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Added a check for last message update and setting last message. 
- The issue was the last message is getting updated with the info message that causing the bidding of submit button.
- Removed the earlier changes.
> [CM-2110] Taxbuddy Assignment Message Issue 

- kommunicate/build.gradle
- kommunicateui/build.gradle
- Increased released version 2.9.10
> Release version increased to 2.9.10

- kommunicate/build.gradle
- kommunicateui/build.gradle
- Updated Release Version to 2.9.11
> Updated release version to 2.9.11

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/network_security_config.xml
- kommunicate/src/main/AndroidManifest.xml
- kommunicate/src/main/res/xml/network_security_config.xml
- kommunicateui/src/main/AndroidManifest.xml
- kommunicateui/src/main/res/xml/network_security_config.xml
In this PR I removed the `usesCleartextTraffic` which sends the data using clear text format. I disabled this and added network config. So, with this default configuration is to communicate over https only. So, with this change all the http calls is disabled for all api's that we are using in **our** code SDK as well as Sample app.
> Added network Config

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/network_security_config.xml
- kommunicate/src/main/AndroidManifest.xml
- kommunicate/src/main/res/xml/network_security_config.xml
- kommunicateui/src/main/AndroidManifest.xml
- kommunicateui/src/main/res/xml/network_security_config.xml
Reverts Kommunicate-io/Kommunicate-Android-Chat-SDK#538
> Revert "Added network Config"

- kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
- kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java
- kommunicate/src/main/java/io/kommunicate/utils/KmUtils.java
- kommunicate/src/main/res/values/strings.xml
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/res/layout/km_device_rooted_layout.xml
- kommunicateui/src/main/res/layout/quickconversion_activity.xml
- kommunicateui/src/main/res/values/strings.xml
Implemented the checks for rooted device in Android SDK. If the device is rooted then they will not be able to login both as visitor and with credentials. If the user is already logged in then they will not be able to access the app and a static screen will be shown to them. **This change also requires the change in Documentation.** 
<image src="https://github.com/user-attachments/assets/21c9429d-3a06-4770-8d4b-870c4f670ff3" />
<video src="https://github.com/user-attachments/assets/943f9a22-dca3-4c91-9223-9544d0ed1fcc" />
> Added checks for root detection in android device.

- app/src/androidTest/java/kommunicate/io/sample/KMUserDataValidationTest.kt
- app/src/androidTest/java/kommunicate/io/sample/data/RegisterUserResponse.kt
- app/src/androidTest/java/kommunicate/io/sample/utils/Utils.kt
Tested the user user meta data by creating the mock user with map of random strings as metadata.
Test cases:
1. `testKmUserAndValidateOnDashboard`
2. `testKmUserWithIncorrectMetaDataAndValidateOnDashboard`
The metadata is cosidered as incorrect if its key value is more than 30 chars.
> Test User meta data. 

- kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java
**Previous Bheaviour**
<video src="https://github.com/user-attachments/assets/8332c6f6-d632-4920-93cd-415f41430cf3" />
**Expected**
<video src="https://github.com/user-attachments/assets/86bee015-c5b1-4d7e-8549-193752f3569b" />
> Fixed the redundant data load on conversation screen.

- kommunicate/build.gradle
- kommunicateui/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/MobicomMultimediaPopupAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Added changes:
1. [Remove unused font. (font awesome)](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/commit/5c816eddf953e2a1bffd226a0931e72aace6a286)
2. [Fixed camera and video icon visible issue when jt is set false in applogics json](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/commit/1391cc98e24da64523b1dbec2359b29f8d03108d)
> Patch 2.10.3 SDK 2.10.4 UI

- app/src/androidTest/java/kommunicate/io/sample/ConversationListTest.kt
- app/src/androidTest/java/kommunicate/io/sample/ConversationTest.kt
- app/src/androidTest/java/kommunicate/io/sample/ConversationWithPreChatTest.kt
- app/src/androidTest/java/kommunicate/io/sample/KMUserDataValidationTest.kt
- app/src/androidTest/java/kommunicate/io/sample/UserDashboardRegistrationTest.kt
- app/src/androidTest/java/kommunicate/io/sample/network/KommunicateChatAPI.kt
- app/src/androidTest/java/kommunicate/io/sample/utils/Utils.kt
- kommunicate/build.gradle
Test cases.
1. ConversationListTest
a. `testOpenConversationListLaunch`
b.  `testConversationCountOfUserAndVerifyConversationOnUIAndFromDashboard`
c.   `testCreateRandomConversationAndOpenWithGroupId`
d.    `testOpenConversationWithInvalidGroupId`
2.  ConversationTest
a. `testCreateSingleThreadConversation`
b. `testLaunchAndSendMessageOnSingleThreadedConversationAndVerifyFromDashboard`
c.  `testLaunchSingleThreadConversationAndVerifyMessagesFromDashboard`
d.  `testLaunchConversationWithPrefillMessageAndValidateMessageFromDashboard`
e.   `testLaunchConversationWithBotIdsAgentIDsTitleTeamId`
> Added Conversation Creation and Launch test.

- app/src/androidTest/java/kommunicate/io/sample/ConversationListOpenTest.kt
- app/src/androidTest/java/kommunicate/io/sample/ConversationListTest.kt
- app/src/androidTest/java/kommunicate/io/sample/ConversationTest.kt
- app/src/androidTest/java/kommunicate/io/sample/ConversationWithPreChatTest.kt
- app/src/androidTest/java/kommunicate/io/sample/KMUserDataValidationTest.kt
- gradle/libs.versions.toml
- kommunicate/build.gradle
- kommunicate/src/main/java/io/kommunicate/KmConversationBuilder.java
- kommunicate/src/main/java/io/kommunicate/network/SSLPinningConfig.kt
- kommunicate/src/main/java/io/kommunicate/utils/KmUtils.kt
- kommunicateui/build.gradle
- settings.gradle
[Fixed Image not downloading issue](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/pull/569/commits/f557052f0fc70ff58873d29ce1572b02b59e612d) - Added SSL pinnning hash
[Fixed Single thread conversation bug.](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/pull/569/commits/aaf7fa2a493a61c822c76d56681062d655f7fcce) - default value is ture
[Ignored root detection for debug apps.](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/pull/569/commits/59b933037827146d640e393b9a11f3e955d8c5c1) - added build config flag
[Updated test cases](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/pull/569/commits/71aec78383c31622f8ca70bfcaed2c87daa29ee8)
[Updated KMUtils to make it compatible with Agent …
> Release SDK with VPAT changes 2.11.0

- app/src/androidTest/java/kommunicate/io/sample/rm/CombinedButtonTest.kt
- app/src/androidTest/java/kommunicate/io/sample/rm/LinkButtonTest.kt
- app/src/androidTest/java/kommunicate/io/sample/rm/SubmitButtonTest.kt
- app/src/androidTest/java/kommunicate/io/sample/rm/SuggestedRepliesTest.kt
- app/src/androidTest/java/kommunicate/io/sample/utils/KmTestHelper.kt
- app/src/androidTest/java/kommunicate/io/sample/utils/Utils.kt
<google-sheets-html-origin><style type="text/css"></style>
21 | RM - Suggested Replied |   |   | 1. Copy the payload from the docs & create intent2. Create conversation from the sdk & trigger that intent3. Check UI rendering & button actions | UI shoudl be rendered properly , Upon tapping the button it should send exact message mapped with it
-- | -- | -- | -- | -- | --
22 | RM - Link Button |   |   | 1. Copy the payload from the docs & create intent2. Create conversation from the sdk & trigger that intent3. Check UI rendering & button actions | UI shoudl be rendered properly , Upon tapping the button it should redirect to the url mapped with the button
23 | RM - Submit Button |   |   | 1. Copy the payload from the docs & create intent2. Create conversation from the sdk & trigger that …
> Added The test for rich messages

- app/build.gradle
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobiComAttachmentSelectorActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobicomLocationActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/webview/KmWebViewActivity.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/utils/InsetHelper.kt
- kommunicateui/src/main/res/layout/activity_km_location.xml
- kommunicateui/src/main/res/layout/mobicom_multi_attachment_activity.xml
- kommunicateui/src/main/res/layout/quickconversion_activity.xml
> Configure SDK for Android 15 edge to edge support

- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/helpers/KmFormStateHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/KmFormStateModel.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmHelper.java
- kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/utils/RichMessageSharedPreference.kt
[Screen_recording_20250327_134700.webm](https://github.com/user-attachments/assets/473eca8b-33bf-485d-b046-2be1f8feb746)
> Persisted Data in Form Rich Message
