Kommunicate-io/Kommunicate-Android-Chat-SDK

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/models/KmAwayMessageResponse.java
* The collectEmail Field used to be boolean earlier, now it is coming as number. Due to this the away message is broken. Adding this commit will fix the away message for android only for this update and above. The previous version will still have the away message broken.
* This was tested on the local device
=> remove collectEmail field from away message response

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
* When the message is already present through MQTT/ FCM, and the sync call goes simultaneously for the same message, the list contains duplicate entries for that message. This happens when creating and launching the conversation simultaneously.
* This is tested on local device with several conversations.
=> fix duplicate message issue when creating a new conversation

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/AlRichMessage.java, kommunicateui/src/main/res/layout/mobicom_sent_message_list_view.xml
**Description**
Fix Rich message - Whenever an invalid json in a chat after a valid JSON then the rich message was repeating itself from the previous one. This has been fixed by hiding the rich message view when no template ID is received in the JSON.
Email Source check - Earlier the email type message had a check for HTML contentType and source == 7. Now the email type message just has check for source == 7. This is because for sent email messages the source
=> Fix rich message repeating issue

CHANGELOG.md, kommunicate/build.gradle, kommunicate/src/main/AndroidManifest.xml, kommunicateui/build.gradle, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java, kommunicateui/src/main/res/layout/mobicom_message_row_view.xml
* Update glide version to the latest
* Fixed the group name not displaying for another group types like the public, private and   broadcast
=> Update glide version to 4.9.0 and release v1.8.4

app/src/main/assets/applozic-settings.json, kommunicate/src/main/AndroidManifest.xml, kommunicate/src/main/java/io/kommunicate/KmChatBuilder.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/async/KmUserLoginTask.java, kommunicate/src/main/java/io/kommunicate/services/KmUserClientService.java, kommunicate/src/main/java/io/kommunicate/users/KMUser.java, kommunicateui/build.gradle, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/ApplozicAudioManager.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java, kommunicateui/src/main/res/layout/km_custom_toolbar_layout.xml, kommunicateui/src/main/res/layout/mobicom_message_list.xml, kommunicateui/src/main/res/values/mobicom_strings.xml
This PR contains the commits for:
1) setting to enable/disable faq option on both screens
2) set default metadata in the new conversation
3) fixed issue where the normal group name is not displaying in conversation screen
4) option to add default metadata in KmChatBuilder
5) The option to merge the message metadata if the keys are similar
6) Delete group functionality
7) Crash fixes and optimisations
This was tested on local device.
=> fix crashes, issues and add metadata merge, delete group features

kommunicate/src/main/java/io/kommunicate/users/KMUser.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
The typing indicator was not unsubscribing from a support group when switched via notification.
Also updated getLoggedInUser method to get the details from contact database.
Tested on real device
=> Fix typing indictor not unsubscribing

kommunicate/src/main/java/io/kommunicate/KmConversationBuilder.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java, kommunicate/src/main/res/values/strings.xml, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/KmFontManager.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/models/KmFontModel.java
Added a new method in KmConversationBuilder that will launch:
1) Launch the conversation list if multiple conversations are there
2) Open the conversation thread in case of a single conversation
3) Create and launch the conversation in case if there are no conversations for the user
All the properties are taken from KmConversationBuilder object.
It works as below:
```java
new KmConversationBuilder(MainActivity.this)
.setAppId(APP_ID)
.launchAndCreateIfEmpty(new KmCallback() {
@Override
public void onSuccess(Object message) {
Utils.printLog(MainActivity.this, "LaunchTest", "Launch and create if empty success : " + message);
}
@Override
public void onFailure(Object error) {
Utils.printLog(MainActivity.this, "LaunchTest", "Launch and create if empty error : " + error);
}
});
```
This is …
=> add launchAndCreateIfEmpty method in conversation builder

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
1) Fixed issue where user was able to send messages even after group is deleted
2) Hide share conversation option in case of deleted groups
=> fix message sending layout not hiding in deleted conversation

kommunicate/src/main/AndroidManifest.xml, kommunicateui/src/main/AndroidManifest.xml, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/ApplozicDocumentView.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ChannelCreateActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ChannelNameActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/FullScreenImageActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Fixed the issue with file provider in case someone uses the same authority as we are using.
This would result in conflict and they will have to change their authority. 
Have appended 'applozic' to the authority to recognize it as our FileProvider
=> fix file provider issue in case of multiple authorities

app/src/main/java/kommunicate/io/sample/MainActivity.java, app/src/main/java/kommunicate/io/sample/pushnotification/FcmListenerService.java, kommunicate/src/main/java/io/kommunicate/KmPreference.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicateui/src/main/AndroidManifest.xml, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/KmFirebaseMessagingService.java
1) Added the push notification service within the SDK. So if someone doesn't have the setup, they do not need to do anything. 
2) If someone already has the setup for push notification, then only 2 steps are required:
**a)** Add the below code in `onNewToken(String s)` method of the Fcm Service:
```
Kommunicate.updateDeviceToken(this, s);
```
**b)** Add the below code in `onMessageReceived(RemoteMessage remoteMessage)` method of the Fcm Service:
```
if (Kommunicate.isKmNotification(this, remoteMessage.getData())) {
return;
}
```
3) No need to call the `registerForPushNotification` method now. Kommunicate will internally check if the deviceToken exists or not, if the tokenExists, push registration will automatically be called.
4) Push registeration will also be called when firebase updates …
=> CM-93 Optimised push notification setup steps

kommunicate/src/main/java/io/kommunicate/KmConversationBuilder.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
* Added a way for adding more users in the group using the builder so that they can add users other than the agent Ids or bot ids.
* Tested with and without adding members in the group works fine.
Testing code: 
```
List<String> agentIds = new ArrayList<>();
agentIds.add("<AGENT_ID>"); // Add AGENT_ID(s) to this list.
List<String> botIds = new ArrayList<>();
botIds.add("BOT_ID");// Add BOT_ID(s) to this list.
List<String> userIds = new ArrayList<>();
userIds.add("userId1");// Add USER id to this list.
userIds.add("userId2");// Add USER id  to this list.
new KmConversationBuilder(MainActivity.this)
.setAgentIds(agentIds)
.setBotIds(botIds)
.setUserIds(userIds)
.createConversation(new KmCallback() {
@Override
public void onSuccess(Object message) {
}
@Override
public void onFailure(Object …
```
=> Added way to sending usersIds from builder.

.github/workflows/stale.yml
Description: Added a workflow to remind and later close inactive issues/PR using Github action bot. It will daily run through GitHub workflow.
Testing: We are using the same workflow in ApplozicSwift repo and it's working fine there.
=> Automation: Remind the participants in case of inactive issue/PR

app/src/main/assets/applozic-settings.json, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmThemeHelper.java
Added static setting to set custom message status icon color. This will override the primary color received from the server.
=> [CM-227] add setting to change message status icon color

kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
This is failing in mobile if someone is uploading their own icon instead of using the pre exisitng ones. In that case the iconIndex field is sending the image name string instead of the index.
=> remove popup and imageIndex field from chat widget model

kommunicate/build.gradle, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/helpers/KmFormStateHelper.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/KmFormStateModel.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java, kommunicateui/src/main/res/layout/km_form_item_layout.xml, kommunicateui/src/main/res/values/strings.xml
* Added support for three types: date, time and datetime-local
* Added support for 24hrs and 12hrs in time
Sample JSON:
```
{
"payload": [
{
"type": "date",     // for date
"data": {
"label": "Date"
}
}, 
{
"type": "time",  //for time
"data": {
"label": "Time",
"amPm": true.      //optional field to set 24 hr and 12 hr time. Set false for 24 hrs
}
},
{
"type": "datetime-local",  //for time
"data": {
"label": "Date & Time",
"amPm": true.      //optional field to set 24 hr and 12 hr time. Set false for 24 hrs
}
]
}
```
=> Add support for date and time picker in form template

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmThemeHelper.java, kommunicateui/src/main/res/values/mobicom_colors.xml
Change:
To change the conversation screen toolbar title and subtitle color now you can add "toolbarTitleColor" and "toolbarSubtitleColor" fields to the applozic-settings.json file. Any error in entry will result in the default being white.
**_Tested locally_**, by going through a simple flow to customize the color, as it would likely be followed by a customer.
Note: Working on moving the toolbar logic to new class. This doesn't concern the issue CM-477 and hasn't been pushed now. It's WIP.
=> CM-477: change toolbar text color from settings file

kommunicate/src/main/java/io/kommunicate/KmConversationBuilder.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
use the below paramter of conversation builder:
```java
new KmConversationBuilder(context)
.setSingleConversation(true)
.setTeamId("52170731")
.launchConversation(new KmCallback() {
@Override
public void onSuccess(Object message) {
dialog.dismiss();
}
@Override
public void onFailure(Object error) {
dialog.dismiss();
}
});
```
This will assign a conversation to the teamId in case of new conversation or update the teamId of an existing conversation.
=> add option to set and update a conversation with teamId

kommunicate/src/main/java/io/kommunicate/utils/KmDateUtils.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/form/KmDropdownItemAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/helpers/KmFormStateHelper.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/KmFormStateModel.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmFormPayloadModel.java, kommunicateui/src/main/res/drawable/ic_arrow_drop_down_black_18dp.xml, kommunicateui/src/main/res/drawable/ic_calendar_today_black_18dp.xml, kommunicateui/src/main/res/drawable/ic_query_builder_black_18dp.xml, kommunicateui/src/main/res/drawable/km_dropdown_background_with_icon.xml, kommunicateui/src/main/res/layout/km_form_item_layout.xml
This PR fixes CM-637 and CM-616
* Added support for dropdown list in form template
* Added Icons for date and time fields in form template
* Changed the UI and post data time and date formats matching web plugin
Some intentional codes:
* Date format as in web is not provided by SImpleDateFormat in Java/Android. So created the format Manually
* Android Spinner needs to have the item displayed by default in the item list. So disabled items will be there in the list at first position. The disabled items are not present in the list in web plugin.
* Form Item Adapter has multiple If/else for different types. This needs to be converted to Adapter factory pattern in future. Added TODO for that.
=> add support for dropdown list in form template

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
* Sync messages on resume of conversationActivity
* For agent app the sync call only fetches conversations from assigned section
* There is a limit of 500 messages on server for sync call to avoid performance issues
=> sync messages on resume of ConversationActivity

kommunicate/src/main/java/com/applozic/mobicomkit/api/HttpRequestUtils.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/account/register/RegisterUserClientService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/UserClientService.java, kommunicate/src/main/java/com/applozic/mobicommons/people/channel/Channel.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java, kommunicate/src/main/java/io/kommunicate/KmSettings.java, kommunicate/src/main/java/io/kommunicate/async/KmAssigneeUpdateTask.java, kommunicate/src/main/java/io/kommunicate/async/KmUpdateConversationTask.java, kommunicate/src/main/java/io/kommunicate/services/KmClientService.java, kommunicate/src/main/java/io/kommunicate/services/KmService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
* Added functionality to update conversation metadata via conversation builder
* Added functionality to update conversationAssignee if a different assignee is passed in the conversation builder
* Moved the updates into parallel tasks so it doesn't affect the response time of conversation builder
* Use the below method to update conversation metadata:
```java
Map<String, String> map = new HashMap<>();
map.put("TicketId", "123456");
map.put("Status", "ActiveNo");
new KmConversationBuilder(context)
//other properties might go here
.setConversationAssignee(newAssignee)
.setConversationMetadata(map)
.launchConversation(new KmCallback() {
@Override
public void onSuccess(Object message) {
}
@Override
public void onFailure(Object error) {
}
});
```
Below test cases are satisfied:
1) If this is a …
=> add functionality to update conversation metadata and assignee

build.gradle, kommunicate/build.gradle
After this change is release with version 2.1.7, customers don't have to do the extra step of adding the jsfrog URL in their project level build.gradle file. The URL will be added by kommunicate module's build.gradle file automatically to the project level buidl.gradle file.
The below step will not be required:
```
repositories {
maven {
url 'https://kommunicate.jfrog.io/artifactory/kommunicate-android-sdk'
}
}
```
=> move kommunicate repo url to library

app/src/main/assets/applozic-settings.json, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java, kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/KmRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmCardRMAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmRichMessageAdapterFactory.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ButtonKmRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/CardTypeKmRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/FaqKmRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ImageKmRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ListKmRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmThemeHelper.java
* If the setting is enabled, all the rich messages after the last sent message will be visible
* The buttons not having any type in card/list will not be affected since the check is only based on the type
* In web currently only quick replies are hidden, I have provided setting for hiding all three types, links, submit and quickReply.
=> add support for hidePostCTA setting

kommunicate/src/main/java/io/kommunicate/services/KmUserClientService.java, kommunicateui/build.gradle
To fix this error:
`Could not GET 'https://google.bintray.com/flexbox-layout/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom'. Received status code 403 from server: Forbidden`
The previous dependency was deprecated.
Flexbox: 
> Starting from 3.0.0, the groupId is changed to com.google.android.flexbox in preparation to uploading the artifacts to google maven. You can still download the artifacts from jcenter for the past versions with the prior groupId (com.google.android), but migrating the library 3.0.0 is recommended.
=> Flexbox groupID changed

kommunicate/src/main/java/io/kommunicate/services/KmUserClientService.java
- `application/<key>/bot/<botID>` endpoint could be removed from the bot server, so changed to KM API URL: `api.kommunicate.io`.
=> Use KM API URL for bot details

kommunicate/src/main/java/com/applozic/mobicommons/people/channel/Channel.java
- Conversations initiated by bots but had no reply should not show up in the Agent App
- Those conversations have Conversation Status = -1
=> [ TD- 1828 ] Invalid conversation showing in Agent app fix

kommunicate/src/main/java/com/applozic/mobicomkit/api/authentication/AlAuthService.java
To fix this crash: java.lang.IllegalArgumentException; View not attached to window manager
While the conversations are getting fetched, a ProgressDialog is shown. When the async task to fetch the conversations is done, the dialog is dismissed. If the activity is destroyed or changed while the async task is running, it will crash the app and send a crash report to the Firebase server.
To fix this, do not dismiss the dialog when the Activity is finishing or destroyed.. 
isDestroyed has a minimum SDK version of 17. 
For SDk version 16, isFinishing() should work in most of the cases.
=> [TD-2091] - ProgressDialog crash fix

kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java
- Agents should not receive notifications for Bot messages and agents message
removed `if (message.getGroupId() == null)` because it was not of any use, in any case.
=> [TD-2082] - Fix notification for agents

kommunicate/src/main/AndroidManifest.xml
Fix for this issue: https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/issues/212
=> Fix for wrong storage permission on SDK >= 28

kommunicateui/src/main/res/layout/km_rich_message_single_text_item.xml
Previously, Rich Message Action Button was set as maxLines="1" so changed it to "3" to support multiple lines
=> [TD-2049] - Add multi lines to RM action button

kommunicate/src/main/java/com/applozic/mobicomkit/api/ApplozicMqttService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/SyncCallService.java, kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java, kommunicate/src/main/java/io/kommunicate/utils/KmConstants.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/MobiComKitBroadcastReceiver.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmAwayView.java
- Away/online status changed is published to a topic: https://kommunicate.atlassian.net/browse/TD-1641
- Message type is "APPLOZIC_25" - fetches for it, then sends a Broadcast
- Updated the UI when we receive the away/online status
- Away message is stored in cache and API away is only called once.
=> [CM-698] - Update Away/Online status using Mqtt

kommunicateui/src/main/AndroidManifest.xml
Android 11 requires a SpeechRecognition query intent to be added in Manifest, for speech recognition to work.
=> [CM-696] - Speech to Text in Android 11 fix

app/src/main/java/kommunicate/io/sample/MainActivity.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/async/KmUserLoginTask.java, kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java, kommunicate/src/main/java/io/kommunicate/utils/KmConstants.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/activities/LeadCollectionActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/adapters/KmPrechatInputAdapter.java, kommunicateui/src/main/res/layout/activity_km_lead_collection.xml, kommunicateui/src/main/res/values/mobicom_strings.xml
**Feature Description:**
If user enables `Lead Collection` in the Dashboard, In the Chat widget when user clicked` Login AS Visitor`, instead of creating random user, widget will show the `User Lead Collection` Screen and after collecting those details, 
widget will create new User based on those details.
once has been created & registered, chat widget launch
1. conversation list screen if user has multiple conversation.
2. particular previous chat screen if user has only one conversation.
3. create a new conversation & show conversation screen if user has no previous conversation.
=> [TD-2260] Pre Chat Collection Support 

kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/User.java
Changed the default authenticationTypeId to 1 so users will require a valid password to login.
For visitors, they can login without a password.
=> [CM-747] - use default authenticationTypeId same as web sdk

kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/models/KmPrechatInputModel.java, kommunicate/src/main/java/io/kommunicate/utils/KmConstants.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/activities/LeadCollectionActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/adapters/KmPrechatDropdownAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/adapters/KmPrechatInputAdapter.java, kommunicateui/src/main/res/layout/km_prechat_dropdown_layout.xml, kommunicateui/src/main/res/values/mobicom_strings.xml
- Create dropdown list for Prechat lead collection - similar to Web SDK
- Can be created using the same Model as text input Model. Only different is we have to set Element = "select" for dropdown menu, and pass a List of String as options.
```
KmPrechatInputModel dropdownField = new KmPrechatInputModel();
dropdownField.setOptions(Arrays.asList("Kommunicate", "Intentive", "Applozic"));
dropdownField.setPlaceholder("Enter details");
dropdownField.setField("Company");
dropdownField.setElement("select");
```
-Have different viewholder for Dropdown and Text input.
-KmPrechatInputAdapter now checks the element type and then assigns a Viewholder accordingly.
=> [CM-783] - Pre-Chat lead form - Dropdown list

kommunicate/src/main/java/com/applozic/mobicomkit/api/ApplozicMqttService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MessageClientService.java
- When agents are in All Conversation tab, the conversation is not auto sync when end user - bot conversation is going on.
- This happens because Channel status is not refreshed when user replies for the first time
- Fix: Update channel locally when user has replied to a conversation
=> [CM-767] - Auto-sync conversation when Agent is in All Conversation tab

kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'short java.lang.Short.shortValue()' on a null object reference
```
Added null check to Channel and Contact to fix the issue.
=> [CM-735] - Broadcast service crash

app/src/main/assets/applozic-settings.json, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/res/values/mobicom_strings.xml
`messageEditText.setHint(!TextUtils.isEmpty(alCustomizationSettings.getEditTextHintText()) ? alCustomizationSettings.getEditTextHintText() : getString(R.string.enter_message_hint));`
editTextHintText checked for value in alCustomizationSettings (applozic-settings.json) before localization using strings. 
Inside alCustomizationSettings, default value was set so localization using string was not happening.
Removed the default value from alCustomizationSettings  so now localization as well as custom settings will work.
=> Support for Localization of editTextHintText

kommunicate/src/main/java/io/kommunicate/KmConversationBuilder.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java, kommunicate/src/main/java/io/kommunicate/KmSettings.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/async/KMHelpDocsKeyTask.java, kommunicate/src/main/java/io/kommunicate/async/KmGetBotTypeTask.java, kommunicate/src/main/java/io/kommunicate/preference/KmBotPreference.java, kommunicate/src/main/java/io/kommunicate/preference/KmDefaultSettingPreference.java, kommunicate/src/main/java/io/kommunicate/preference/KmPreference.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- To create a default conversation setting, which can be used with "Start new conversation" button on the conversation list page.
- Added these methods:
```java
KmSettings.setDefaultBotIds(List<String> botIds) 
KmSettings.setDefaultAgentIds(List<String> agentIds)
KmSettings.setDefaultAssignee(String assigneeId)
KmSettings.setDefaultTeamId(String teamId)
KmSettings.clearDefaultSettings()
```
- Saves the settings to KmDefaultSettingPreference. To clear the default data, `KmSettings.clearDefaultSettings()` can be used.
- Also, modified existing preference for better code structure.
=> [CM-939] - Added support to set default conversation settings

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/FullScreenImageActivity.java, kommunicateui/src/main/res/layout/mobicom_image_full_screen.xml
- GIFs were not handled by the SDK. Every image was being shown as a Bitmap image, hence GIFs were not animating.
- Added a check to see if Image coming is a GIF. If it's a GIF, load it in a different image viewer as an animating drawable.
- Zooming in is not possible for GIF images.
- Images can come from 2 places: Normal upload and Rich Message payload. Added support for GIF in both.
=> [CM-943] - Added support for GIFs

kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComConversationService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java, kommunicate/src/main/java/com/applozic/mobicomkit/channel/service/ChannelClientService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/MobiComKitBroadcastReceiver.java
- Empty Message is coming if handover option is added in welcome message.
- Extra message object is been added with only having metadata of `"KM_ASSIGN_TO" : "id"`.thatswhy empty message in showing on device side
- deviceside create new channel endpoint is older version when comparing to chat widget's
- added `KM_ASSIGN_TO,KM_ASSIGN_TEAM` flags to Action Message category & removing messages.
- updated the create channel endpoint same as web chat widget
- Web chat widget following the same way of handling
=> [CM-961] Blank message if handover option is added

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Crash was happening because getString requires context and context was not getting null in some case.
- Get context from ApplozicService.getContext()
=> [CM-995] - ConversationFragment not attached to a context crash

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/KmDocumentView.java
Added a null check at KMDocumentView.java : 352 which removes the crashing
=> [CM-1038] Crash Fix while calling getName() at KmDocumentView.java:352

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/api/attachment/FileClientService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MessageClientService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/FullScreenImageActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- Happens only with slow internet: If you send multiple attachments at once, sometimes server gives 502 response code. This response code was not handled by device and message was being sent as empty message.
- Empty message in dashboard:
- Exception will be caught when any other response comes, other than 200. This will be handled by showing retry option in attachment. When you click retry, attachments are sent.
- Retry option:
=> [CM-1037] - fix for attachment not sent

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/api/ApplozicMqttService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/SyncCallService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/selfdestruct/DisappearingMessageTask.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/MobiComPushReceiver.java, kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/MobiComKitBroadcastReceiver.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Messages which are deleted from dashboard were not handled by SDK.
- Getting deleted message event from MQTT and API: `/rest/ws/message/sync/metadataUpdate`
- Deleting message from database and updating the UI 
- Decreasing the unread count whenever a message is deleted
https://user-images.githubusercontent.com/22256112/184812967-ac1f02ba-c5c1-4159-8af9-dc8c945b4e61.mp4
=> [CM-1005] - Sync deleted messages

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/channel/service/ChannelClientService.java, kommunicate/src/main/java/com/applozic/mobicomkit/sync/SyncChannelFeed.java
List v3 API provides a lot of unnecessary data which are not required, because of which we are getting outOfMemoryError. 
To fix this, upgrade the list api to v5.
Schema is same, only difference is that v5 API does not give group member details for every group
=> [CM-1063] - Upgrade channel list API to v5

kommunicate/src/main/java/com/applozic/mobicomkit/channel/service/ChannelService.java, kommunicate/src/main/java/com/applozic/mobicomkit/sync/SyncChannelFeed.java
- Crash was happening when groupPxy was returned as null from server. 
- To fix, added a null check as well as try catch block
=> Channel sync crash fix

kommunicate/src/main/java/com/applozic/mobicomkit/api/account/register/RegisterUserClientService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/people/UserIntentService.java, kommunicate/src/main/java/com/applozic/mobicomkit/channel/service/ChannelService.java, kommunicate/src/main/java/com/applozic/mobicommons/people/channel/Channel.java, kommunicate/src/main/java/io/kommunicate/async/KmSyncMessageTask.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobiComKitActivityInterface.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, local.properties
Getting **Application Not Responding** when local database is big in size
- We were using "synchronized" method calls at some places where it was not required. Using synchronized method calls block the other thread while the current thread is doing the work in that class. It was also blocking the main thread at some places.
- Database Input / Output were done in main thread. It was causing performance issue.
- Removed "synchronized" method calls wherever it's not necessary. We do not need synchronized calls as we are already sending a Broadcast to update the UI. With this, no other threads will be blocked, and UI will also be updated whenever necessary.
- Added Channel User Mapper to Channel Data class. With this, we do not need to access the Database everytime to get channel user …
=> [CM-1094] - SDK Optimization 

kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/ConversationDatabaseService.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java, kommunicate/src/main/java/com/applozic/mobicomkit/contact/database/ContactDatabase.java, kommunicate/src/main/java/com/applozic/mobicommons/commons/core/utils/DBUtils.java, kommunicate/src/main/java/io/kommunicate/services/KmChannelService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- execSQL and rawQuery methods are vulnerable to SQL Injection. For customers who require good security, this needs to be updated.
- Concatenated queries with values are vulnerable to SQL Injection. For example:  `db.rawQuery("SELECT unreadCount FROM contact WHERE userId = " + "'" + userId + "'", null);` should be updated to `db.query("contact", new String[]{"unreadCount"}, "userId = ?", new String[]{userId}, null, null, null);`
Changed the above methods to .update and .query which uses Arguments[] as values, rather than concatenating the query with values. These arguments are sanitized by Android SDK to prevent SQL injection.
- Created a method to update/query methods which were changed and compared using old and new value.
```
2022-09-14 15:09:48.860 12780-30859/io.kommunicate.app …
```
=> [CM-1072] - Replace execSQL and rawQuery with .query and .update

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Toolbar was showing invalid name 
The last message fetched was of Agent, but the conversation assignee was a bot. It was giving priority to the last message sent's contact rather than the assignee.
Changed the priority of fetching name for toolbar. First, it would check for Channel Assignee. if that is null, then it would check for contact's name.
https://user-images.githubusercontent.com/22256112/190099720-04e177d4-7671-4158-b21d-20d66df3a16f.mp4
=> [CM-1111] - fix for invalid agent/bot name

app/src/main/AndroidManifest.xml
- This Sample app is using old api key & it was causing issue in location preview
- It won't affect anything in sdk side. We are not setting any default google api key for sdk. This configuration needs to be done from client side. Doc: https://docs.kommunicate.io/docs/reactnative-customization#hidingshowing-media-attachment-and-location-sharing-options
=> [CM-1146] Updated the api key for sample app

app/src/main/AndroidManifest.xml, kommunicate/src/main/AndroidManifest.xml, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/KmAudioRecordManager.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmRecordView.java, migration/Migrate to 2.5.0.md
- We had permissions for Camera, Microphone, Location and External Storage in SDK. Due to this, even if a customer who does not require these feature, would show these permissions in Google Play as well as App Settings.
- Removed these permissions from SDK and  moved them to Project level
- Written a migration documentation
=> [CM-1139] - Remove Permissions from SDK

CHANGELOG.md, app/build.gradle, app/src/main/AndroidManifest.xml, kommunicate/build.gradle, kommunicate/src/main/java/com/applozic/mobicommons/commons/core/utils/PermissionsUtils.java, kommunicateui/build.gradle
<html>
<body>
<p style="box-sizing: inherit; margin: 16px 0px; padding: 0px; color: rgb(32, 33, 36); font-family: Roboto, &quot;Noto Sans&quot;, &quot;Noto Sans JP&quot;, &quot;Noto Sans KR&quot;, &quot;Noto Naskh Arabic&quot;, &quot;Noto Sans Thai&quot;, &quot;Noto Sans Hebrew&quot;, &quot;Noto Sans Bengali&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If your app targets Android 13 or …
=> [CM-1161] - Added support for storage permissions in API 33

kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
From the Serializable interface's [docs](http://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html):
`If a serializable class does not explicitly declare a serialVersionUID, then the serialization runtime will calculate a default serialVersionUID value for that class based on various aspects of the class, as described in the Java(TM) Object Serialization Specification. However, it is strongly recommended that all serializable classes explicitly declare serialVersionUID values, since the default serialVersionUID computation is highly sensitive to class details that may vary depending on compiler implementations, and can thus result in unexpected InvalidClassExceptions during deserialization. Therefore, to guarantee a consistent serialVersionUID value across different java compiler …
=> [CM-994]- Fix Serialized Class crash - Message.java

kommunicate/build.gradle, kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/UserLogoutTask.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MessageClientService.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java, kommunicate/src/main/java/io/kommunicate/services/KmZendeskClient.java, kommunicate/src/main/java/io/kommunicate/utils/KmAppSettingPreferences.java, kommunicate/src/main/java/io/kommunicate/utils/KmConstants.java, kommunicate/src/main/java/io/kommunicate/zendesk/KmZendeskClient.java, kommunicate/src/main/res/values/strings.xml, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- To Support Zopim Integration in Android SDK, used Zendesk Chat SDK V2:
`implementation group: 'com.zendesk', name: 'chat-providers', version: '3.3.0'`
- Identify Zendesk User and storing the Zendesk Account key in local storage
- Create new flow for opening Zendesk conversation - 
`Kommunicate.openZendeskChat(context)`
- Updating source of conversation for Zendesk user
- Send Chat Transcript to Zendesk when handoff happens
=> [CM-1190 - Zendesk base integration

kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/MobiComPushReceiver.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java, kommunicate/src/main/java/com/applozic/mobicomkit/feed/InstantMessageResponse.java
- Show notification when "Send notification alert to mobile devices" is enabled from notification test page
=> [CM-1238] - Show notification from Notification Test Page

kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/utils/KmConstants.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- We need to expose a method to Hybrid platforms to close the application through code.
- If they use events to navigate their app, navigation will happen but our application will be shown on top. To fix this, we have added support to close our application, which can be exposed to Hybrid platforms.
=> Add support to close conversation screen from code

kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlEventManager.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- React Native showing "Handler sending message to a Handler on a dead thread " when an event is triggered
_Each Handler has a Looper, and a Looper is associated with a Thread (usually a HandlerThread). The general problem is when a Handler becomes associated with thread that stops running. If someone tries to use the Handler, it will fail with the message "sending message to a Handler on a dead thread"._
- Any easy fix is to construct your Handler like,
`Handler h = new Handler(Looper.getMainLooper());`
This associates the Handler with the main looper, or the main application thread which will never die (good for things like callbacks, but not for any blocking work obviously).
=> Create UI thread for events in MainLooper

CHANGELOG.md, kommunicate/build.gradle, kommunicateui/build.gradle
1) Added support to send platform flag for analytics
2) Added logout option on conversation screen
3) Stopped calling refresh token API when proper parameters are not passed.
4) Send actual Notification from Notification test page
5) Handle notification from FCM directly
6) Add support to close Kommunicate Application through code
7) Threads optimized for Hybrid platforms
8) Multiple crash fixes
=> release changes for v2.6.0

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/utils/KmViewHelper.java
Previously inside the `updateSupportGroupTitleAndImageAndHideSubtitle` function there was no separate case for agent app so even when the toolbar was of agent app it was working as a toolbar of SDK which is fixed now
=> [CM-1309] Fixed agent app toolbar showing conversation assignee image instead of end user image

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java, kommunicate/src/main/java/com/applozic/mobicomkit/channel/database/ChannelDatabaseService.java, kommunicate/src/main/java/com/applozic/mobicomkit/contact/database/ContactDatabase.java, kommunicate/src/main/java/io/kommunicate/database/KmAutoSuggestionDatabase.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Removed all the raw queries from the database as they are vulnerable to SQL injection attacks and converted them to either prepared statements or query methods or the arguments passed in the raw query are used as replaceable parameters instead of directly using it inside the SQL query . The processes for mitigation were taken from the documentation  which stated that _Using ? as a replaceable parameter in selection clauses and a separate array of selection arguments binds the user input directly to the query rather than interpreting it as part of an SQL statement._ More information can be found in the [docs](https://developer.android.com/topic/security/risks/sql-injection#mitigations).
```
Cursor cursor = null;
cursor = database.rawQuery("SELECT COUNT(*) FROM channel WHERE channelKey=?", …
```
=> [CM-1299] Removed SQL injection vulnerability from the SDK

kommunicate/src/main/java/com/applozic/mobicommons/file/FileUtils.java
- To expose customization to Hybrid platforms, we will be having a method "FileUtils.writeSettingsToFile(string)"
- This method will be called from Hybrid platforms along with a JSON string.
- This will create a local file in the device "kommunicate-settings.json". We will be reading this file whenever settings are required.
- I have used this code in React Native Android, which is working fine.
=> [CM-1306] - Read and write settings from local file

CHANGELOG.md, app/src/main/assets/applozic-settings.json, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Added customization to hide/show restart conversation button in Android SDK where the user can set the value for `"restartConversationButtonVisibility"` in the `applozic-settings.json` file to change the visibility of the button
=> [CM-1307] Added customization for restart conversation button

kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmRMActionModel.java
- Added support to send hidden message
- Added support for metadata for Action Message on Form Template
- Added Support for hiding message on form submission based on metadata
- if metadata contains `  "category": "HIDDEN"` submission message will be hidden on user end. it will be visible on dashboard
You can see` submitted my details` only visible at dashboard end not at user end
=> [CM-1327] - Hide User submitted message on form submission

CHANGELOG.md, kommunicate/build.gradle, kommunicateui/build.gradle
1) Added customization for restart conversation button
2) Removed SQL injection vulnerability from the Android SDK
3) Added support to set multiple Speech To Text language
4) Added option to enable/disable JavaScript in WebView
5) Restricted Zoom In / out on web view of FaqActivity
6) Added option to rate conversation anytime from the conversation menu
7) Metadata from form submission action payload to message replyMetadata
8) Read and Write settings to local app file
=> release changes for v2.6.5

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java, migration/Migrate to 2.X.X.md
- FormData was stringified twice. First, just the "formData" object was stringified. Second, the whole message body was stringified
- Because of this, formData was getting stringified twice.
- Fixed this by storing the formData as an object
=> [CM-1363] - Match formData with web

kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlEventManager.java, kommunicate/src/main/java/com/applozic/mobicomkit/listners/KmConversationInfoListener.java, kommunicate/src/main/java/io/kommunicate/preference/KmConversationInfoSetting.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmConversationInfoView.java, kommunicateui/src/main/res/drawable/km_files.xml, kommunicateui/src/main/res/drawable/km_next.xml, kommunicateui/src/main/res/layout/km_conversation_info_layout.xml, kommunicateui/src/main/res/layout/mobicom_message_list.xml
- Added Support for conversation info view which will be added below to the navigation bar on conversation screen
- Added Event for conversation info tap action
- Added customisation for conversation info view
``` java
KmConversationInfoSetting.getInstance(SplashScreenActivity.this)
.setInfoContent("Check out your ITR Summary")
.setContentColor("#FFFFFF")
.setBackgroundColor("#05A3BF")
.setTrailingImageIcon("km_next")
.setLeadingImageIcon("km_files")
.enableKmConversationInfo(true);
```
=> [CM-1365] - add support to show conversation info view below topbar

app/src/main/java/kommunicate/io/sample/MainActivity.java, kommunicate/src/main/java/io/kommunicate/preference/KmConversationInfoSetting.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/res/drawable/km_home.xml, kommunicateui/src/main/res/layout/km_custom_toolbar_layout.xml, kommunicateui/src/main/res/values/colors.xml, kommunicateui/src/main/res/values/mobicom_themes.xml, kommunicateui/src/main/res/values/strings.xml
-Added support for custom toolbar in which user can set agent experience and agent rating
-Added support to change colour of back button
- Add this code into MainActivity.java in the Kommunicate login method:
```
//To enable the new Custom toolbar Design
KmConversationInfoSetting.getInstance(getApplicationContext()).enableCustomToolbarSubtitleDesign(true);
//Setting up the agent experience
KmConversationInfoSetting.getInstance(getApplicationContext()).setToolbarAgentExperience("<agent_experience>");     
//Setting up the agent rating
KmConversationInfoSetting.getInstance(getApplicationContext()).setToolbarSubtitleRating((float) <agent_rating>);
```
- To change colour of back button add this code to 'colors.xml':
```
<color name="km_back_button_colour">#03A9F4</color>
```
=> [CM-1368] - Support for custom toolbar subtitle

app/src/main/assets/applozic-settings.json, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MessageListTask.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/res/drawable/km_lock.xml, kommunicateui/src/main/res/drawable/km_top_first_message.xml, kommunicateui/src/main/res/layout/km_static_top_message.xml
- To add a top message, which will be part of the recycler view, meaning it could be scrolled out of view
- Add this to custom settings json file:
```json
"staticTopMessage": "Messages in this chat are encrypted. No one outside this chat can read them",
"staticTopIcon": "km_lock"
```
- By default, the top message will not show
=> [CM-1371] - Add support to add top first message

kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/res/drawable/km_blinking_dot.xml, kommunicateui/src/main/res/layout/km_typing_indicator_layout.xml, kommunicateui/src/main/res/values/colors.xml
1. Changed Recycler view layout from bottom to top TO top to Bottom. Messages will start coming from top now.
2. Changed typing indicator design to match web sdk. Typing indicator will show where the message will come.
- Tested it on my local device
=> [CM-1373] - Changed Recycler View layout to Top to Bottom 

kommunicate/src/main/java/com/applozic/mobicomkit/Applozic.java, kommunicate/src/main/java/com/applozic/mobicommons/data/AlPrefSettings.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java, kommunicate/src/main/java/io/kommunicate/utils/KmConstants.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- Device language code is passed to the GroupMetadata and MessageMetadata.
- `KM_CHAT_CONTEXT: "{\"kmUserLocale\":\"en\"}"`
- Tested it on the  local device
=> [CM-1390] - Passing LanguageCode to GroupMetadata and MessageMetadata

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/RichMessageActionProcessor.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmRMActionModel.java
-  Added a new field `addFormLabelInMessage` to the `KmRMActionModel` class, which controls whether or not to show the form label in the message when the form data is submitted
- If `addFormLabelInMessage` is set to false, only the value of the field will be included in the message, without the label.
=> [CM-1441] - Add support on form data as message flow with only submitted responses

kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlMessageEvent.java, kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/MobiComKitBroadcastReceiver.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java
- To expose a method that allows the text in the chat to be populated from an external source.
- The method provide flexibility for external components to set the desired text and update the chat interface accordingly.
- use 'setChatText' method in 'kommunicate.java' class, pass context and desired string to the method
=> [CM-1433] - Expose Method to populate text on chat bar

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Fixed NullPointerException  caused by 'setChannel' method in MobiComConversationFragment.java
=> [CM-1418] - Agent app Crash - KmConversationFragment.setChannel

CHANGELOG.md, kommunicate/build.gradle, kommunicateui/build.gradle
1) Added support for Custom Input Field
2) Added Restriction for Start Plan in Android SDK
3) Added team concept in companySettings
4) Fixed a bug in which user Unable to retrieve all conversation list in the agent app(While using latest SDK).
=> release changes for v2.7.2

kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/AlMessageEvent.java, kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/MobiComKitBroadcastReceiver.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Exposed a method 'hideAssigneeStatus' in Kommunicate.class
- In this method we have to pass context and a boolean value
- For 'hide' -> true, will hide offline/online and away status
- For 'hide' -> false, will show  offline/online and away status
=> [CM - 1498] - Expose a function to show/hide online, offline,away status

kommunicate/src/main/java/io/kommunicate/async/KmGetDataAsyncTask.java, kommunicate/src/main/java/io/kommunicate/services/KmHttpClient.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/models/v2/KmAutoSuggestion.java
- To fetch AutoSuggestion data from API
- API will be called after 2nd alphabet, for every alphabet - This approach is better than storing all the data locally.
```json
{"data": [
{
"searchKey": "option1",
"message": "option 1"
},
{
"searchKey": "option2",
"message": "option 2"
},
{
"searchKey": "option3",
"message": "option 3"
},
{
"searchKey": "option4",
"message": "option 4"
},
{
"searchKey": "option5",
"message": "option 5"
},
{
"searchKey": "option6",
"message": "option 6"
},
{
"searchKey": "option7",
"message": "option 7"
},
{
"searchKey": "option8",
"message": "option 8"
},
{
"searchKey": "option9",
"message": "option 9"
},
{
"searchKey": "option10",
"message": "option 10"
},
{
"searchKey": "option11",
"message": "option 11"
}
]
}
```
=> [CM-1473] - add support for autosuggest through API

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java, kommunicateui/src/main/res/layout/mobicom_message_list.xml
- "Start new conversation" button is not visible few times. 
- It is happening because by default the start new conversation is not not visible. When the settings file is not available when the conversation was opened, the the button will not show.
- By default, the visibility of Start new conversation is set to VISIBLE. From settings, we can change it to visible.
=> [CM-1276] - change default visibility of startNewConversation button

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Fixed null pointer caused by KmToast.makeText.
=> [CM-1516] - Android Agent app crash - LayoutInflater null pointer

CHANGELOG.md, kommunicate/build.gradle, kommunicateui/build.gradle
1) Change default visibility of startNewConversation button
2) Away message visibility effects
3) Fixed crashes
=> Release changes for V2.7.6

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/channel/database/ChannelDatabaseService.java
Added a function to get a map of channel and last message created time as a key-value pair in order to update the conversation history in agent app. For detailed info -> [CM-1503 Agent App](https://github.com/Kommunicate-io/AgentApp/pull/295)
=> Updated ChannelDatabaseService.java to add Conversation History in Agent App

kommunicateui/src/main/res/layout/km_custom_toolbar_layout.xml
- Fixed the refresh icon distortion reported by MG
=> [CM-1529] - Refresh icon squeezed on conversation screen | Android

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/adapters/KmLanguageSelectionAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/models/KmSpeechToTextModel.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/settings/KmSpeechToTextSetting.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/views/KmLanguageSlideView.java
- Added support to trigger an intent when language is selected for speech to text
- Created KmSpeechToTextModel class to use it on Multiple Language support for Speech to Text
- This is can be enabled like below
```
List<KmSpeechToTextModel> list = new ArrayList<>();
KmSpeechToTextModel m1 = new KmSpeechToTextModel("en", "English", "Change language to English", true);
KmSpeechToTextModel m2 = new KmSpeechToTextModel("hi", "Hindi", "Change language to Hindi", true);
KmSpeechToTextModel m3 = new KmSpeechToTextModel("zh", "Chinese", "Change language to Chinse", true);
list.add(m1);
list.add(m2);
list.add(m3);
KmSpeechToTextSetting.getInstance(SplashScreenActivity.this).setSpeechToTextList(list)
.enableMultipleSpeechToText(true)
.sendMessageOnSpeechEnd(true)
.showLanguageCode(false);
```
=> [CM-1524]- add support to send message on language change

CHANGELOG.md, kommunicate/build.gradle, kommunicateui/build.gradle
1) Added support to send message on language change
2) Show/Hide Template message buttons when resolved conversation
3) Fixed refresh icon squeeze and crashes
=> release changes for v2.7.7

kommunicateui/src/main/res/layout/feedback_rating_layout.xml, kommunicateui/src/main/res/values/mobicom_strings.xml, kommunicateui/src/main/res/values/strings.xml, kommunicateui/src/main/res/values/styles.xml
- Made changes to make menu items appear below the Action Bar area
- Changed the text of feedback rating(Good -> Great)
- Changed the hint for conversation_message textview("Write a message…" -> "Type your message...")
=> [CM-1570] - to make menu items appear below the Action Bar area

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmFormItemAdapter.java
Earlier the drop down list of form type rich message is clashing with the spinner layout which is fixed
=> [CM-1572] Added DropDownVerticalOffset for Form type rich message

CHANGELOG.md, kommunicate/build.gradle, kommunicateui/build.gradle
1) Fixed dropdown list of spinner in form type rich message clashing with the spinner layout
2) Added customization to center toolbar title and left align message templates
=> release changes for v2.7.8

kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java
- Duplicate conversation were showing in the conversation list 
- This issue Was happening because of wrong SQL query in MessageDatabaseService class
- Tested on local release build
=> [CM-1586] - Getting duplicate data on recycler view (conversation list)

kommunicate/src/main/java/com/applozic/mobicommons/data/SecureSharedPreferences.java, kommunicate/src/main/java/com/applozic/mobicommons/encryption/SecurityUtils.java
-  This issue happens when user uninstall the app(Without clearing the app data) and the reinstall the app again.
- Problem arises because there is already AES key is present in the sharedPreferences and it is encrypted with old RSA keyPair(public and private key) so when the app is installed again the app generates new RSA keyPair so it cannot decrypt the old AES key
- For this we clear the sharedPreferences and then generatesAES key, encrypt it, store it to shared pref and return the un-encrypted version 
- Tested basic functionality of the agent app locally
=> [CM-1556] - NullPointerException When trying to login in agent app

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/res/layout/quickconversion_activity.xml
=> [customizations-for-mg] Fixed toolbar title alignment when menu options are enabled/disabled

CHANGELOG.md, kommunicate/build.gradle, kommunicateui/build.gradle
1) Fixed toolbar title not in center when menu option is disabled
2) Fixed getting duplicate data on conversation list when using latest SDK(Agent app)
3) Bug fixes
=> Release changes v2.7.9

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
When message templates were null the app was crashing which is fixed by adding a check.
To reproduce the crash remove the following code from  `applozic-settings.json` , build the app and go to conversation screen. 
```
"messageTemplate": {
"isEnabled": false,
"isLeftAligned" : false,
"borderColor": "#5c5aa7",
"backgroundColor": "#FFFFFF",
"hideOnSend": false,
"sendMessageOnClick": true,
"cornerRadius": 30,
"textColor": "#5c5aa7",
"messageList": {
"Greetings": "Hey",
"Help?": "How may I help you?",
"Email-Id": "May I know your emailId",
"Company": "May I know your company name?",
"Platform?": "Is this related to Android, iOS, or web?",
"Doc?": "Did you follow our doc?"
}
},
```
=> [CM-1653] Fixed message template crash

CHANGELOG.md, app/src/main/assets/applozic-settings.json, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/KmFormRichMessage.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/utils/KmThemeHelper.java
Previously when the hidePostCTA was enabled for submit button it was also hiding the form action button, hence made a separate configuration for form's action button so that both the configurations become independent.
=> [CM-1705] Added hidePostCTA configuration for form action button

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Previously, if we set the delay for bot message, there was no delay for the welcome message and the typing indicator was appearing after the welcome message was received which is fixed here.
=> [CM-1239] Fixed typing indicator appearing after welcome message was received

app/src/main/assets/applozic-settings.json, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- Earlier by default status bar colour was set from "applozic-settings.json" file.
- Now the colour of status bar will be fetched from chat widget, if a colour is passed on customisation file it will override chat widget colour.
=> [CM-1576] - Status bar theme colour Fix

app/src/main/assets/applozic-settings.json, kommunicate/src/main/java/com/applozic/mobicommons/commons/core/utils/PermissionsUtils.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java
- Fixed an issue in Api 33+ when only images permission is given on manifest file and "IMAGE_ONLY" is set to true in filterGallery (applozic-settings.json) the file explorer will not open
=> [CM-1733] - Attachment option to only provide Images, Videos 

CHANGELOG.md, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- After the deletion of item from message list, adapter was not notified due to which positions of items below the delete item were not correct
=> [CM-1748] Fixed agent app crashing while deleting messages

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/api/ApplozicMqttService.java
Fixed user sent message coming on the RHS in agent app
When the user sends a message, first a MQTT received message is being received in the agent app and then a MQTT sent message is being received in agent app due to which agent app was considering it as a sent message and was showing on the RHS insread of LHS. Hence, added a check to ensure that sent message from MQTT will only be considered when received `sent message user id` and `logged in user id` are same
=> [CM-1762] Fixed user messages coming on right side in agent app

kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicate/src/main/java/io/kommunicate/models/KmAutoSuggestionModel.java, kommunicate/src/main/java/io/kommunicate/services/KmService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Taxbuddy wanted to reassign a conversation back to a bot by using quick replies provided in the dashboard.
We have modified the quickreplies for the same. 
The idea is that they will identify the event at universal webhook and trigger reassignment.
Currently the agent app was not receiving hidden messages, hence added a check to ensure that if a message has `"category":"HIDDEN"`, it is shown in the agent app.
- Provide a way to send specific events along with the quickreplies.
=> Quick reply feature for Taxbuddy

CHANGELOG.md, app/src/main/assets/applozic-settings.json, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/res/layout/km_sent_message_list_view.xml
After the new timestamp was developed in sdk, the message status icon colour customisation was only available while enabling inner time stamp design which is fixed now.
After changing `"messageStatusIconColor"` to "`#0000FF"`
=> [CM-1766] Fixed message status icon colour customisation issue

app/src/main/assets/applozic-settings.json
Earlier in our sample app the sent message background color was not changing with change in dashboard theme which is fixed now.
=> [CM-1797] Fixed sent message icon color not changing in sample app

CHANGELOG.md, app/src/main/assets/applozic-settings.json, kommunicate/src/main/java/com/applozic/mobicommons/file/FileUtils.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobiComAttachmentSelectorActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/MobiComAttachmentGridViewAdapter.java
Added customisation to allow users to select multiple attachments while sending from gallery
[Screen_recording_20240108_120053.webm](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/assets/139108613/ae984624-7ad5-496d-8a37-3103710c15a6)
The code was tested with API Level 22,29,30 and 33.
=> [CM-1824] Added customization for multiple attachment selection

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- There were unnecessary API calls happening in the agent app for group list which is fixed
- Fixed KmConversationFragment.onResume crash
- Fixed away message showing even after conversation is assigned to bot
=> [CM-1864] group list API optimizations

kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/callbacks/KmChatWidgetCallback.java, kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- Client can disable chat widget on dashboard.Once it is disabled , web chat widget will not popup on website.
- To match with the same feature, we have exposed an function to get this config value set from dashboard
```
Kommunicate.isChatWidgetDisabled(new KmChatWidgetCallback() {
@Override
public void onResult(boolean isDisabled) {
if (isDisabled) {
// Can add the code to hide chat icon or button on the app
} else {
//Can add the code to show chat icon or button on the app
}
}
});
```
=> [CM-914]-Added support for chatwidget disabled flag

CHANGELOG.md, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComMessageService.java, kommunicate/src/main/java/com/applozic/mobicomkit/broadcast/BroadcastService.java
- As the message is not having conversation assignee name , so the agent was not receiving notifications after automatic assignment which is fixed now.
- Tested agent app notifications and verified that they are working fine and all notifications are getting received from fcm except `assigned to <agent name>`
- Tested sdk notifications and verified that they are also working fine and all notifications are getting received from fcm now
=> [CM-1907] Fixed agent app not showing notifications after automatic assignment

kommunicate/src/main/java/io/kommunicate/utils/KmUtils.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/QuickConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComQuickConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/adapters/KmCardRMAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/types/ButtonKmRichMessage.java, kommunicateui/src/main/res/layout/mobicom_message_list.xml, kommunicateui/src/main/res/values/mobicom_colors.xml
-  Added dark mode support for all conversation activity
- As of now this is hidden, we will be enabling it after whole dark mode is completed
=> [CM-1458] Added dark mode support part - 1

kommunicate/src/main/java/io/kommunicate/Kommunicate.java, kommunicate/src/main/java/io/kommunicate/utils/KMAgentStatusHelper.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/ConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Update the user status dynamically based on any condition
- once this is set, It will show irrespective of the original status
- Formatted the MobicomconversationFragment File
- Just call below function before opening the conversation or during the conversation . It will update the status
```java
Kommunicate.updateAssigneeStatus("" , KMAgentStatusHelper.KMAgentStatus.AWAY);
```
- If you pass the valid assignee id , status will be changed for only that assignee.
- If you pass empty string on assignee id, status will changed irrespective of assignee
=> [CM-1953] Added support for updating agent status dynamically

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java
- The DOM API was disabled within the webview we utilized for loading HTML content. Consequently, iframes were unable to render, as this API is essential for storing data in the browser's local storage.
=> [CM-1950] Enable DOM storage 

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobicomLocationActivity.java
When the user clicks on the location button but his location is not enabled, android provides a pop up from which the user can go to location settings and can enable location. In this case, when the user comes back to the app after enabling location he was not able to send location which is fixed now.
=> [CM-1966] Fix location issue in Android SDK

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/richmessaging/webview/KmWebViewActivity.java, kommunicateui/src/main/res/layout/km_activity_payment.xml
- When a link-type rich message is clicked, the application will now open the link within an in-app browser that previously lacked a back button, but now includes one.
=> [CM-1903] Added back button in app browser

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/FullScreenImageActivity.java, kommunicateui/src/main/res/layout/mobicom_image_full_screen.xml
- Fixed toolbar of full screen imageview colliding with the status bar on devices having notch in the screen.
- Tested with both type of devices i.e, devices having notch screen and devices which are not having notch screen.
- Tested with devices having screen size 5" inch to 6.67" inches.
=> [CM-1904] Image full screen view improvement

CHANGELOG.md, app/src/main/assets/applozic-settings.json, kommunicate/src/main/java/com/applozic/mobicommons/file/FileUtils.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/async/FileTaskAsync.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/ConversationUIService.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobiComAttachmentSelectorActivity.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/KmAttachmentsController.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/kommunicate/callbacks/PrePostUIMethods.java
Add these 2 fields inside `applozic-settings.json` to compress a image before sending
```
"isImageCompressionEnabled": true, // default value is false
"minimumCompressionThresholdForImagesInMB": 10 // default value is 5 MB
```
=> [CM-1978] Added customization for image compression

app/src/main/assets/applozic-settings.json, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Exposed a customization in `applozic-settings.json` as `"hideAttachmentOptionsBeforeHandover": false` so that Attachments Options can be hidden when bot handles the chat. Once handoff happened (human assignee) Attachment Options should be visible.
=> [CM-1452] - Attachment options visibility customization

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Removed Image + Video Preview screen in the capture image/video flow.
<table>
<tr>
<th colspan="3"><b> Before <b/></th>
</tr>
<tr>
<td> <img width="120" src="https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/assets/162960364/8a217b8a-8257-4d44-958e-7c1aa2e44db8" /></td>
<td> <img width="120" src="https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/assets/162960364/206bb2d0-05d5-483f-b5e7-87a6699c1915"/> </td>
<td> <img width="120" src="https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/assets/162960364/bb62d643-7ff8-4084-8962-06a9984e33f3"/> </td>
</tr>
</table>
<table>
<tr>
<th colspan="3"><b> After<b/></th>
</tr>
<tr>
<td> <img width="120" src="https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/assets/162960364/8a217b8a-8257-4d44-958e-7c1aa …
=> [CM-2039] Remove image and video preview screen | Android SDK

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
Removed the `Delete for all` option from the agent app. Now we have only `Delete` option. However funtionality for this `Delete` option will work similar to:
- `Delete for all` if the `message.isTypeOutbox`  is `true`
- `Delete` if the `message.isTypeOutbox` is `false`
| Before | After |
|---|---|
| <img width="250" src="https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/assets/162960364/f0501a84-e375-43d6-8039-5abaf4ff76b7" /> | <img width="250" src="https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/assets/162960364/e143bc81-5ef8-40c6-b7ab-780ac4ba17eb" /> |
=> [CM-1185] - Delete For All option fix | Android Agent App

app/src/main/assets/applozic-settings.json
Added `useDarkMode` missing flag in `applozic-settings.json`.
true:
- SDK theme will toggle dark/light mode depending upon android theme
false (default):
- SDK theme will be in light mode irrespective of android theme
=> DarkMode missing flag

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
- Fixed the team mode crash happened due to `requireContext()`.
- Added check for agent app at top level then only call the restrict function, eventually reducing function call.
=> team mode crash fix

kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/KmDocumentView.java
- Added a tap gesture of mainLayout if the file is downloaded  
- The attachment bubble will work only when the file is downloaded. User needs to click on download button to download.
https://github.com/user-attachments/assets/327f9421-dded-4870-8d02-572f95e171f7
=> [CM-2128] Improve Tap Gesture for attachments | Android SDK 

kommunicate/src/main/java/io/kommunicate/models/KmAppSettingModel.java
- Restricted setup of take over from bot for the parameter of `conversation.takeOverFromBot` in AppSetting response.
=> [CM-2120] Hide Take Over From Bot | Android Agent App

app/src/main/java/kommunicate/io/sample/MainActivity.java, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java, kommunicate/src/main/java/io/kommunicate/Kommunicate.java
- Earlier the issue was that when the user tried to build conversation with preChat, it used to show default Pre Chat Screen with empty fields
- The function (launchConversationWithPreChat) was not in use and this function (launchConversationWithPreChat) was calling an important function (checkForLeadCollection).
- So I made use of this function in the (createOrLaunchConversation) function in KmConversationHelper.java, where it performs creation as well as the launch of conversation.
- After that, it is working fine, and whenever a user will try to do setwithPreChat, then they will get desired results as attached below
=> CM-2127 PreChat Labels not visible when Configured from dashboard | Android SDK

.gitignore, app/build.gradle, app/src/main/AndroidManifest.xml, build.gradle, gradle/libs.versions.toml
In this PR I used the google-secret library for storing the api keys. In this we have to put api key in `local.properties` which is ingored by `.gitignore`. So, API key wont be present in our repo anymore. If we don't put the api key in `local.properties` then App build will fail by throwing this error. 
For the sdk user's they will not face any crash. They have to manage their api key on there own. 
```
Merge Errors Error: Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:65:13-42 requires a placeholder substitution but no value for <GOOGLE_KEY> is provided. Kommunicate-Android-Chat-SDK.app main manifest (this file), line 64
```
=> Removed Hardcoded Maps API Key

kommunicate/src/main/java/com/applozic/mobicomkit/Applozic.java
- Updated the key for language change from `kmUserLanguageCode` to `kmUserLocale`.  (Similar to iOS and Web)
=> [CM-2206] Language Code update in ChatContext | Android SDK

app/src/main/assets/applozic-settings.json, kommunicate/build.gradle, kommunicate/src/main/java/com/applozic/mobicomkit/Applozic.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/account/user/User.java, kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java, kommunicateui/build.gradle, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/AlCustomizationSettings.java, kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
In this patch release :
1. Hide chatbar
2. Fixed redundant loading issue
3. Updated langauge code
=> Patch 2.10.2 SDK and 2.10.3 UI

app/src/androidTest/java/kommunicate/io/sample/ConversationListTest.kt, kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
**Approach**
Did the API call for checking the conversation exist for the given APP ID. If it does not exists then I will raise the exception which is handled by the callback `onFailure` method. 
Verified with IOS we are following the same approach there.
=> [BUG] Open conversation is opening with invalid Conversation ID

kommunicate/src/main/java/io/kommunicate/network/SSLPinningConfig.kt
In this I added a check of root detection in the SSL Pinning. If the device is rooted It will throw the exception and no API calls will happen. This helps us in avoiding the intercepting and changing the certificate. 
The new Root Device Detection logic can't be bypassed and It also checks for frida. 
Alternative approach for this is to write the SSL pinning logic in the NDK in CPP files to avoid is getting bypassed. 
<video src="https://github.com/user-attachments/assets/9e8a313c-b245-4a6f-9353-2f52b40005ae" />
=> Added Root Device Detection in SSL Pinning

app/build.gradle, app/src/androidTest/java/kommunicate/io/sample/ConversationTest.kt, app/src/androidTest/java/kommunicate/io/sample/FAQTest.kt, app/src/androidTest/java/kommunicate/io/sample/network/KommunicateChatAPI.kt, app/src/androidTest/java/kommunicate/io/sample/network/KommunicateDashboardAPI.kt, app/src/androidTest/java/kommunicate/io/sample/utils/KmTestHelper.kt, gradle/libs.versions.toml
1. [ConversationTest.kt](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/compare/development...CM-2218-Automation-Tests-for-FAQ-Update-Conversation-Language-Change-and-Assignee-Change-Android-SDK?expand=1#diff-c9d9cab4a9138ba4c409976cd312984e03a9793050d79e00601526878cd777e3)
a. `testUpdateConversationAssigneeAndVerifyFromDashboard`
b. `testUpdateConversationTeamIdAndVerifyFromDashboard`
c.  `testConversationWithLanguageChange`
d.   `testChangeAssigneeFromDashboardAndVerifyStatusOnSDK`
2. [FAQTest.kt](https://github.com/Kommunicate-io/Kommunicate-Android-Chat-SDK/compare/development...CM-2218-Automation-Tests-for-FAQ-Update-Conversation-Language-Change-and-Assignee-Change-Android-SDK?expand=1#diff-6758f0125a7b39f253af56cc2466a329cd2dec557a423503b6e2f92a6ce54a2b)
a. …
=> Automation tests for faq update conversation language change and assignee change

kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
Added the check for single theaded conversation is set programatically.
states
1. enable on server and enable on app -> conversation is single threaded.
2. enable on server and disable on app -> conversation is single threaded.
3. disable on server and enable on app -> conversation is single threaded.
4. disable on server and disable on app -> conversation is  not single threaded. (Bheaviour similar from IOS)
=> Fixed: Unable to create single threaded conversation programatically
